// Code generated by goctl and unified for api-thinktalk. DO NOT EDIT.
package types

// ==================== User, Member, Social & Tag Types ====================
type LoginRequest struct {
	Mobile           string `json:"mobile"`
	VerificationCode string `json:"verification_code,optional"`
	Password         string `json:"password,optional"`
}

type LoginResponse struct {
	UserId int64 `json:"userId"`
	Token  Token `json:"token"`
}

type RegisterRequest struct {
	Name             string `json:"name"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserInfoResponse struct {
	UserId       int64  `json:"user_id"`
	Username     string `json:"username"`
	Avatar       string `json:"avatar"`
	Role         int64  `json:"role"`
	DisplayId    string `json:"display_id"`
	Bio          string `json:"bio"`
	Gender       int32  `json:"gender"`
	ProfileCover string `json:"profile_cover"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}

type ThumbupRequest struct {
	BizId    string `json:"biz_id"`
	ObjId    int64  `json:"obj_id"`
	LikeType int32  `json:"like_type"`
}

type ThumbupResponse struct {
	BizId     string `json:"biz_id"`
	ObjId     int64  `json:"obj_id"`
	LikeNum   int64  `json:"like_num"`
	DislikeNum int64 `json:"dislike_num"`
}

type IsThumbupRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
}

type IsThumbupResponse struct {
	LikeType    int32 `json:"like_type"`
	ThumbupTime int64 `json:"thumbup_time"`
}

type FollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type FollowResponse struct{}

type UnfollowRequest struct {
	FollowedUserId int64 `json:"followed_user_id"`
}

type UnfollowResponse struct{}

type FollowListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FollowItem struct {
	Id               int64  `json:"id"`
	FollowedUserId   int64  `json:"followed_user_id"`
	CreateTime       int64  `json:"create_time"`
	FansCount        int64  `json:"fans_count"`
	TargetUserName   string `json:"target_user_name"`
	TargetUserAvatar string `json:"target_user_avatar"`
}

type FollowListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type FansListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FansListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type NotificationRequest struct {
	Type     int32 `form:"type"`
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type NotificationItem struct {
	Id            int64  `json:"id"`
	Type          int32  `json:"type"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	IsRead        bool   `json:"is_read"`
	TriggerUserId int64  `json:"trigger_user_id"`
	RefId         int64  `json:"ref_id"`
	CreateTime    int64  `json:"create_time"`
}

type NotificationResponse struct {
	Items  []*NotificationItem `json:"items"`
	Cursor int64               `json:"cursor"`
	IsEnd  bool                `json:"is_end"`
}

type UnreadCountResponse struct {
	Total      int64           `json:"total"`
	TypeCounts map[int32]int64 `json:"type_counts"`
}

type MarkReadRequest struct {
	NotificationId int64 `json:"notification_id"`
}

type MarkReadResponse struct{}

type MarkAllReadRequest struct {
	Type int32 `json:"type"`
}

type ConcernedAddRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedAddResponse struct{}

type ConcernedCancelRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedCancelResponse struct{}

type ConcernedCheckRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ConcernedCheckResponse struct {
	IsConcerned bool `json:"is_concerned"`
}

type ConcernedListRequest struct {
	BizId    string `form:"biz_id"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type ConcernedItem struct {
	Id         int64  `json:"id"`
	BizId      string `json:"biz_id"`
	ObjId      int64  `json:"obj_id"`
	CreateTime int64  `json:"create_time"`
}

type ConcernedListResponse struct {
	Items  []*ConcernedItem `json:"items"`
	Cursor int64            `json:"cursor"`
	IsEnd  bool             `json:"is_end"`
}

type MemberInfoResponse struct {
	UserId     int64  `json:"user_id"`
	Level      int32  `json:"level"`
	LevelName  string `json:"level_name"`
	ExpireTime int64  `json:"expire_time"`
	Status     int32  `json:"status"`
}

type MemberRightRequest struct {
	RightKey string `form:"right_key"`
}

type MemberRightResponse struct {
	HasRight bool  `json:"has_right"`
	Level    int32 `json:"level"`
}


type TagCreateRequest struct {
	TagName string `json:"tag_name"`
	TagDesc string `json:"tag_desc"`
}

type TagCreateResponse struct {
	TagId int64 `json:"tag_id"`
}

type TagUpdateRequest struct {
	TagId   int64  `json:"tag_id"`
	TagName string `json:"tag_name"`
	TagDesc string `json:"tag_desc"`
}

type TagUpdateResponse struct{}

type TagDeleteRequest struct {
	TagId int64 `json:"tag_id"`
}

type TagDeleteResponse struct{}

type TagDetailRequest struct {
	TagId int64 `form:"tag_id"`
}

type TagItem struct {
	TagId         int64  `json:"tag_id"`
	TagName       string `json:"tag_name"`
	TagDesc       string `json:"tag_desc"`
	ResourceCount int64  `json:"resource_count"`
	CreateTime    int64  `json:"create_time"`
}

type TagDetailResponse = TagItem

type TagListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type TagListResponse struct {
	Items  []*TagItem `json:"items"`
	Cursor int64      `json:"cursor"`
	IsEnd  bool       `json:"is_end"`
}

type HotTagsRequest struct {
	Limit int32 `form:"limit"`
}

type HotTagsResponse struct {
	Items []*TagItem `json:"items"`
}

type TagResourceRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
	TagId    int64  `json:"tag_id"`
}

type TagResourceResponse struct{}

type UntagResourceRequest struct {
	BizId    string `json:"biz_id"`
	TargetId int64  `json:"target_id"`
	TagId    int64  `json:"tag_id"`
}

type UntagResourceResponse struct{}

type ResourcesByTagRequest struct {
	TagId    int64  `form:"tag_id"`
	BizId    string `form:"biz_id,optional"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type ResourceItem struct {
	TargetId   int64  `json:"target_id"`
	BizId      string `json:"biz_id"`
	CreateTime int64  `json:"create_time"`
}

type ResourcesByTagResponse struct {
	Items  []*ResourceItem `json:"items"`
	Cursor int64           `json:"cursor"`
	IsEnd  bool            `json:"is_end"`
}

type TagsByResourceRequest struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
}

type TagsByResourceResponse struct {
	Items []*TagItem `json:"items"`
}


type ReplyCreateRequest struct {
	BizId         string `json:"biz_id"`
	TargetId      int64  `json:"target_id"`
	BeReplyUserId int64  `json:"be_reply_user_id,omitempty"`
	ParentId      int64  `json:"parent_id,omitempty"`
	Content       string `json:"content"`
}

type ReplyCreateResponse struct {
	ReplyId int64 `json:"reply_id"`
}

type ReplyDeleteRequest struct {
	ReplyId int64 `json:"reply_id"`
}

type ReplyDeleteResponse struct{}

type ReplyDetailRequest struct {
	ReplyId int64 `form:"reply_id"`
}

type ReplyItem struct {
	ReplyId         int64        `json:"reply_id"`
	BizId           string       `json:"biz_id"`
	TargetId        int64        `json:"target_id"`
	ReplyUserId     int64        `json:"reply_user_id"`
	BeReplyUserId   int64        `json:"be_reply_user_id"`
	ParentId        int64        `json:"parent_id"`
	Content         string       `json:"content"`
	LikeNum         int64        `json:"like_num"`
	CreateTime      int64        `json:"create_time"`
	ReplyUserName   string       `json:"reply_user_name"`
	ReplyUserAvatar string       `json:"reply_user_avatar"`
	SubReplies      []*ReplyItem `json:"sub_replies,omitempty"`
}

type ReplyDetailResponse struct {
	Reply *ReplyItem `json:"reply"`
}

type ReplyListRequest struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
	SortType int32  `form:"sort_type,optional"`
}

type ReplyListResponse struct {
	Items  []*ReplyItem `json:"items"`
	Cursor int64        `json:"cursor"`
	IsEnd  bool         `json:"is_end"`
}

type ReplyCountRequest struct {
	BizId    string `form:"biz_id"`
	TargetId int64  `form:"target_id"`
}

type ReplyCountResponse struct {
	ReplyNum     int64 `json:"reply_num"`
	ReplyRootNum int64 `json:"reply_root_num"`
}


type ConcernedCountRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ConcernedCountResponse struct {
	ConcernedNum int64 `json:"concerned_num"`
}


type UpgradeMemberRequest struct {
	Level         int32  `json:"level"`
	DurationDays  int32  `json:"duration_days"`
	TransactionId string `json:"transaction_id"`
	Amount        int64  `json:"amount"`
	PayChannel    string `json:"pay_channel"`
}

type UpgradeMemberResponse struct{}

type MemberOrderListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type MemberOrderItem struct {
	Id           int64  `json:"id"`
	UserId       int64  `json:"user_id"`
	Level        int32  `json:"level"`
	DurationDays int32  `json:"duration_days"`
	Amount       int64  `json:"amount"`
	PayChannel   string `json:"pay_channel"`
	Status       int32  `json:"status"`
	CreateTime   int64  `json:"create_time"`
}

type MemberOrderListResponse struct {
	Items  []*MemberOrderItem `json:"items"`
	Cursor int64              `json:"cursor"`
	IsEnd  bool               `json:"is_end"`
}

type AdminReplyListRequest struct {
	Keyword  string `form:"keyword,optional"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type AdminReplyListResponse struct {
	Items  []*ReplyItem `json:"items"`
	Cursor int64        `json:"cursor"`
	IsEnd  bool         `json:"is_end"`
}

type AdminUserListRequest struct {
	Keyword  string `form:"keyword,optional"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type AdminUserItem struct {
	UserId       int64  `json:"user_id"`
	Username     string `json:"username"`
	Mobile       string `json:"mobile"`
	Avatar       string `json:"avatar"`
	Role         int64  `json:"role"`
	DisplayId    string `json:"display_id"`
	Bio          string `json:"bio"`
	Gender       int32  `json:"gender"`
	ProfileCover string `json:"profile_cover"`
	CreateTime   int64  `json:"create_time"`
}

type AdminUserListResponse struct {
	Items  []*AdminUserItem `json:"items"`
	Cursor int64            `json:"cursor"`
	IsEnd  bool             `json:"is_end"`
}

type CreateMemberOrderReq struct {
	Level        int32  `json:"level"`
	DurationDays int32  `json:"duration_days"`
	Amount       int64  `json:"amount"`
	PayChannel   string `json:"pay_channel"`
}

type CreateMemberOrderResp struct {
	OrderSn string `json:"order_sn"`
	Amount  int64  `json:"amount"`
	PayUrl  string `json:"pay_url"`
}

type QueryOrderStatusReq struct {
	OrderSn string `json:"order_sn"`
}

type QueryOrderStatusResp struct {
	OrderSn     string `json:"order_sn"`
	Status      int32  `json:"status"`       // 0=待支付 1=已支付 2=已退款
	StatusText  string `json:"status_text"`  // "待支付" / "已支付" / "已退款"
	TradeNo     string `json:"trade_no"`     // 支付宝交易号（已支付时返回）
	TotalAmount string `json:"total_amount"` // 支付宝返回的交易金额（元）
}

type UpdateProfileRequest struct {
	Username     string `json:"username"`
	Avatar       string `json:"avatar,optional"`
	Bio          string `json:"bio,optional"`
	Gender       int32  `json:"gender,optional"`
	ProfileCover string `json:"profile_cover,optional"`
}

type UpdateProfileResponse struct{}

type NotificationMsg struct {
	UserId        int64  `json:"user_id"`
	Type          int32  `json:"type"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	RefId         int64  `json:"ref_id"`
	BizId         string `json:"biz_id"`
	TriggerUserId int64  `json:"trigger_user_id"`
}

type UserProfileRequest struct {
	UserId int64 `form:"userId"`
}

type UserProfileResponse struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
}


type AdminBroadcastNotificationRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type AdminBroadcastNotificationResponse struct {
	SuccessCount int64  `json:"success_count"`
	TotalCount   int64  `json:"total_count"`
}


type DeleteNotificationRequest struct {
	NotificationId int64 `json:"notification_id"`
}

type DeleteNotificationResponse struct {
}


type AdminDeleteReplyRequest struct {
	ReplyId int64 `json:"reply_id"`
}

type AdminDeleteReplyResponse struct {
}

// ==================== Article Types ====================
type AdminAuditRequest struct {
	ArticleId int64 `json:"article_id"`
	Status    int32 `json:"status"` // 2: approve (visible), 1: reject (not pass)
}

type AdminAuditResponse struct {
}

type AdminPendingListRequest struct {
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type AdminPendingListResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type AllArticlesRequest struct {
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type AllArticlesResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type ArticleDeleteRequest struct {
	ArticleId int64 `json:"article_id"`
}

type ArticleDeleteResponse struct {
}

type ArticleDetailRequest struct {
	ArticleId int64 `form:"article_id,optional"`
}

type ArticleDetailResponse struct {
	ArticleId    int64  `json:"article_id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Description  string `json:"description"`
	Cover        string `json:"cover"`
	AuthorId     int64  `json:"author_id"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
	PublishTime  string `json:"publish_time"`
	LikeNum      int64  `json:"like_num"`
}

type ArticleInfo struct {
	ArticleId   int64  `json:"article_id"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Description string `json:"description"`
	Cover       string `json:"cover"`
	Status      int64  `json:"status"`
}

type ArticleListRequest struct {
	AuthorId  int64 `form:"author_id,optional"`
	Cursor    int64 `form:"cursor,optional"`
	PageSize  int64 `form:"page_size,optional"`
	SortType  int32 `form:"sort_type,optional"`
	ArticleId int64 `form:"article_id,optional"`
}

type ArticleListResponse struct {
	Articles []ArticleInfo `json:"articles"`
}

type PublishRequest struct {
	Title       string  `json:"title"`
	Content     string  `json:"content"`
	Description string  `json:"description"`
	Cover       string  `json:"cover"`
	TagIds      []int64 `json:"tag_ids,optional"`
}

type PublishResponse struct {
	ArticleId int64 `json:"article_id"`
}

type SearchInfo struct {
	ArticleId    int64  `json:"article_id"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	Cover        string `json:"cover"`
	AuthorId     int64  `json:"author_id"`
	AuthorName   string `json:"author_name"`
	LikeNum      int64  `json:"like_num"`
	CommentNum   int64  `json:"comment_num"`
	PublishTime  string `json:"publish_time"`
	AuthorAvatar string `json:"author_avatar"`
}

type SearchRequest struct {
	Keyword  string `form:"keyword"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type SearchResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type UploadCoverResponse struct {
	CoverUrl string `json:"cover_url"`
}

// ==================== Chat Types ====================
const DefaultPageSize = 20

type SendMessageRequest struct {
	ReceiverId int64  `json:"receiver_id"`
	Content    string `json:"content"`
	MsgType    int32  `json:"msg_type"`
}

type SendMessageResponse struct{}

type ConversationsRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type ConversationItem struct {
	Id               int64  `json:"id"`
	TargetUserId     int64  `json:"target_user_id"`
	TargetUserName   string `json:"target_user_name"`
	TargetUserAvatar string `json:"target_user_avatar"`
	LastMessage      string `json:"last_message"`
	LastMessageTime  int64  `json:"last_message_time"`
	UnreadCount      int64  `json:"unread_count"`
}

type ConversationsResponse struct {
	Items  []*ConversationItem `json:"items"`
	Cursor int64               `json:"cursor"`
	IsEnd  bool                `json:"is_end"`
}

type MessagesRequest struct {
	ConversationId int64 `form:"conversation_id"`
	Cursor         int64 `form:"cursor"`
	PageSize       int64 `form:"page_size"`
}

type MessageItem struct {
	Id             int64  `json:"id"`
	ConversationId int64  `json:"conversation_id"`
	SenderId       int64  `json:"sender_id"`
	ReceiverId     int64  `json:"receiver_id"`
	Content        string `json:"content"`
	MsgType        int32  `json:"msg_type"`
	IsRead         bool   `json:"is_read"`
	CreateTime     int64  `json:"create_time"`
}

type MessagesResponse struct {
	Items  []*MessageItem `json:"items"`
	Cursor int64          `json:"cursor"`
	IsEnd  bool           `json:"is_end"`
}

type ChatMarkReadRequest struct {
	ConversationId int64 `json:"conversation_id"`
}

type ChatMarkReadResponse struct{}

type ChatUnreadCountResponse struct {
	Total int64 `json:"total"`
}

type MessageResponse struct {
	Id             int64  `json:"id"`
	ConversationId int64  `json:"conversation_id"`
	SenderId       int64  `json:"sender_id"`
	ReceiverId     int64  `json:"receiver_id"`
	Content        string `json:"content"`
	MsgType        int32  `json:"msg_type"`
	CreateTime     int64  `json:"create_time"`
}

type WsInMessage struct {
	Type        string `json:"type"`
	ReceiverId  int64  `json:"receiver_id,omitempty"`
	Content     string `json:"content,omitempty"`
	MsgType     int32  `json:"msg_type,omitempty"`
	ClientMsgId string `json:"client_msg_id,omitempty"`
}

type WsOutMessage struct {
	Type        string `json:"type"`
	SenderId    int64  `json:"sender_id,omitempty"`
	Content     string `json:"content,omitempty"`
	MsgType     int32  `json:"msg_type,omitempty"`
	CreateTime  int64  `json:"create_time,omitempty"`
	Message     string `json:"message,omitempty"`
	ClientMsgId string `json:"client_msg_id,omitempty"`
}

// ==================== QA Types ====================
type PublishQuestionRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	TagIds  string `json:"tag_ids"`
}

type PublishQuestionResponse struct {
	QuestionId int64 `json:"question_id"`
}

type AnswerQuestionRequest struct {
	QuestionId int64  `json:"question_id"`
	Content    string `json:"content"`
}

type AnswerQuestionResponse struct {
	AnswerId int64 `json:"answer_id"`
}

type AcceptAnswerRequest struct {
	QuestionId int64 `json:"question_id"`
	AnswerId   int64 `json:"answer_id"`
}

type QuestionDetailRequest struct {
	QuestionId int64 `form:"question_id"`
}

type QuestionListRequest struct {
	AuthorId int64 `form:"author_id,optional"`
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
	SortType int32 `form:"sort_type,optional"`
}

type QuestionItem struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	AuthorId   int64  `json:"author_id"`
	AnswerNum  int64  `json:"answer_num"`
	ViewNum    int64  `json:"view_num"`
	TagIds     string `json:"tag_ids"`
	CreateTime int64  `json:"create_time"`
}

type QuestionListResponse struct {
	Items  []*QuestionItem `json:"items"`
	Cursor int64           `json:"cursor"`
	IsEnd  bool            `json:"is_end"`
}

type QuestionDetailResponse struct {
	Question *QuestionItem `json:"question"`
}

type QuestionDeleteRequest struct {
	QuestionId int64 `json:"question_id"`
}

type AnswerListRequest struct {
	QuestionId int64 `form:"question_id"`
	Cursor     int64 `form:"cursor"`
	PageSize   int64 `form:"page_size"`
}

type AnswerItem struct {
	Id         int64  `json:"id"`
	QuestionId int64  `json:"question_id"`
	AuthorId   int64  `json:"author_id"`
	Content    string `json:"content"`
	IsAccepted bool   `json:"is_accepted"`
	LikeNum    int64  `json:"like_num"`
	ReplyNum   int64  `json:"reply_num"`
	CreateTime int64  `json:"create_time"`
}

type AnswerListResponse struct {
	Items  []*AnswerItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type AnswerDeleteRequest struct {
	AnswerId int64 `json:"answer_id"`
}

type SearchQuestionsRequest struct {
	Keyword  string `form:"keyword"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type SearchQuestionItem struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	AuthorId   int64  `json:"author_id"`
	AnswerNum  int64  `json:"answer_num"`
	TagIds     string `json:"tag_ids"`
	CreateTime int64  `json:"create_time"`
}

type SearchQuestionsResponse struct {
	Items  []*SearchQuestionItem `json:"items"`
	Cursor int64                 `json:"cursor"`
	IsEnd  bool                  `json:"is_end"`
}

// ==================== Agent Types ====================
type ChatRequest struct {
	SessionID string `json:"session_id,optional"`
	Message   string `json:"message"`
}

type HistoryRequest struct {
	SessionID string `form:"session_id"`
}

type HistoryResponse struct {
	SessionID string        `json:"session_id"`
	Title     string        `json:"title"`
	Messages  []AgentMessageItem `json:"messages"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
}

type AgentMessageItem struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type StopRequest struct {
	SessionID string `json:"session_id"`
}

type SessionItem struct {
	SessionID    string `json:"session_id"`
	Title        string `json:"title"`
	MessageCount int32  `json:"message_count"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type ListSessionsResponse struct {
	Sessions []SessionItem `json:"sessions"`
}

type DeleteSessionRequest struct {
	SessionID string `json:"session_id"`
}

type DeleteSessionResponse struct {
	Success bool `json:"success"`
}
