// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AcceptAnswerRequest struct {
	QuestionId int64 `json:"question_id"`
	AnswerId   int64 `json:"answer_id"`
}

type AdminAuditRequest struct {
	ArticleId int64 `json:"article_id"`
	Status    int32 `json:"status"`
}

type AdminAuditResponse struct {
}

type AdminBroadcastNotificationRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type AdminBroadcastNotificationResponse struct {
	SuccessCount int64 `json:"success_count"`
	TotalCount   int64 `json:"total_count"`
}

type AdminBroadcastRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type AdminBroadcastResponse struct {
}

type AdminDeleteReplyRequest struct {
	ReplyId int64 `json:"reply_id"`
}

type AdminDeleteReplyResponse struct {
}

type AdminPendingListRequest struct {
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type AdminPendingListResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type AdminReplyListRequest struct {
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type AdminReplyListResponse struct {
	Items  []*ReplyItem `json:"items"`
	Cursor int64        `json:"cursor"`
	IsEnd  bool         `json:"is_end"`
}

type AdminUserInfo struct {
	UserId       int64  `json:"user_id"`
	Username     string `json:"username"`
	Avatar       string `json:"avatar"`
	Role         int64  `json:"role"`
	DisplayId    string `json:"display_id"`
	Bio          string `json:"bio"`
	Gender       int32  `json:"gender"`
	ProfileCover string `json:"profile_cover"`
}

type AdminUserListRequest struct {
	Keyword  string `form:"keyword,optional"`
	Cursor   int64  `form:"cursor,optional"`
	PageSize int64  `form:"page_size,optional"`
}

type AdminUserListResponse struct {
	Users  []AdminUserInfo `json:"users"`
	Cursor int64           `json:"cursor"`
	IsEnd  bool            `json:"is_end"`
}

type AgentMessageItem struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type AllArticlesRequest struct {
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type AllArticlesResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type AnswerDeleteRequest struct {
	AnswerId int64 `json:"answer_id"`
}

type AnswerItem struct {
	Id         int64  `json:"id"`
	QuestionId int64  `json:"question_id"`
	AuthorId   int64  `json:"author_id"`
	Content    string `json:"content"`
	IsAccepted bool   `json:"is_accepted"`
	LikeNum    int64  `json:"like_num"`
	ReplyNum   int64  `json:"reply_num"`
	CreateTime int64  `json:"create_time"`
}

type AnswerListRequest struct {
	QuestionId int64 `form:"question_id"`
	Cursor     int64 `form:"cursor"`
	PageSize   int64 `form:"page_size"`
}

type AnswerListResponse struct {
	Items  []*AnswerItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type AnswerQuestionRequest struct {
	QuestionId int64  `json:"question_id"`
	Content    string `json:"content"`
}

type AnswerQuestionResponse struct {
	AnswerId int64 `json:"answer_id"`
}

type ArticleDeleteRequest struct {
	ArticleId int64 `json:"article_id"`
}

type ArticleDeleteResponse struct {
}

type ArticleDetailRequest struct {
	ArticleId int64 `form:"article_id,optional"`
}

type ArticleDetailResponse struct {
	ArticleId    int64  `json:"article_id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Description  string `json:"description"`
	Cover        string `json:"cover"`
	AuthorId     int64  `json:"author_id"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
	PublishTime  string `json:"publish_time"`
	LikeNum      int64  `json:"like_num"`
}

type ArticleInfo struct {
	ArticleId   int64  `json:"article_id"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Description string `json:"description"`
	Cover       string `json:"cover"`
	Status      int64  `json:"status"`
}

type ArticleListRequest struct {
	AuthorId  int64 `form:"author_id,optional"`
	Cursor    int64 `form:"cursor,optional"`
	PageSize  int64 `form:"page_size,optional"`
	SortType  int32 `form:"sort_type,optional"`
	ArticleId int64 `form:"article_id,optional"`
}

type ArticleListResponse struct {
	Articles []ArticleInfo `json:"articles"`
}

type ChatMarkReadRequest struct {
	ConversationId int64 `json:"conversation_id"`
}

type ChatMarkReadResponse struct {
}

type ChatRequest struct {
	SessionID string `json:"session_id,optional"`
	Message   string `json:"message"`
}

type ChatUnreadCountResponse struct {
	Total int64 `json:"total"`
}

type ConcernedAddRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedAddResponse struct {
}

type ConcernedCancelRequest struct {
	BizId string `json:"biz_id"`
	ObjId int64  `json:"obj_id"`
}

type ConcernedCancelResponse struct {
}

type ConcernedCheckRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ConcernedCheckResponse struct {
	IsConcerned bool `json:"is_concerned"`
}

type ConcernedCountRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ConcernedCountResponse struct {
	Count int64 `json:"count"`
}

type ConcernedItem struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"user_id"`
	BizId      string `json:"biz_id"`
	ObjId      int64  `json:"obj_id"`
	CreateTime int64  `json:"create_time"`
}

type ConcernedListRequest struct {
	BizId    string `form:"biz_id"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type ConcernedListResponse struct {
	Items  []*ConcernedItem `json:"items"`
	Cursor int64            `json:"cursor"`
	IsEnd  bool             `json:"is_end"`
}

type ConversationItem struct {
	Id               int64  `json:"id"`
	TargetUserId     int64  `json:"target_user_id"`
	TargetUserName   string `json:"target_user_name"`
	TargetUserAvatar string `json:"target_user_avatar"`
	LastMessage      string `json:"last_message"`
	LastMessageTime  int64  `json:"last_message_time"`
	UnreadCount      int64  `json:"unread_count"`
}

type ConversationsRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type ConversationsResponse struct {
	Items  []*ConversationItem `json:"items"`
	Cursor int64               `json:"cursor"`
	IsEnd  bool                `json:"is_end"`
}

type CreateMemberOrderReq struct {
	Level        int32  `json:"level"`
	DurationDays int32  `json:"duration_days"`
	Amount       int64  `json:"amount"`
	PayChannel   string `json:"pay_channel"`
}

type CreateMemberOrderResp struct {
	OrderSn string `json:"order_sn"`
	Amount  int64  `json:"amount"`
	PayUrl  string `json:"pay_url"`
}

type DeleteNotificationRequest struct {
	Id int64 `json:"id"`
}

type DeleteNotificationResponse struct {
}

type DeleteSessionRequest struct {
	SessionID string `json:"session_id"`
}

type DeleteSessionResponse struct {
	Success bool `json:"success"`
}

type FansItem struct {
	Id             int64  `json:"id"`
	FansId         int64  `json:"fans_id"`
	FansName       string `json:"fans_name"`
	FansAvatar     string `json:"fans_avatar"`
	FansBio        string `json:"fans_bio"`
	IsMutualFollow bool   `json:"is_mutual_follow"`
	CreateTime     int64  `json:"create_time"`
}

type FansListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FansListResponse struct {
	Items  []*FansItem `json:"items"`
	Cursor int64       `json:"cursor"`
	IsEnd  bool        `json:"is_end"`
}

type FollowItem struct {
	Id             int64  `json:"id"`
	FollowId       int64  `json:"follow_id"`
	FollowName     string `json:"follow_name"`
	FollowAvatar   string `json:"follow_avatar"`
	FollowBio      string `json:"follow_bio"`
	IsMutualFollow bool   `json:"is_mutual_follow"`
	CreateTime     int64  `json:"create_time"`
}

type FollowListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type FollowListResponse struct {
	Items  []*FollowItem `json:"items"`
	Cursor int64         `json:"cursor"`
	IsEnd  bool          `json:"is_end"`
}

type FollowRequest struct {
	FollowId int64 `json:"follow_id"`
}

type FollowResponse struct {
}

type HistoryRequest struct {
	SessionID string `form:"session_id"`
}

type HistoryResponse struct {
	SessionID string             `json:"session_id"`
	Title     string             `json:"title"`
	Messages  []AgentMessageItem `json:"messages"`
	CreatedAt int64              `json:"created_at"`
	UpdatedAt int64              `json:"updated_at"`
}

type HotTagsRequest struct {
	Limit int32 `form:"limit,optional"`
}

type HotTagsResponse struct {
	Items []*TagItem `json:"items"`
}

type IsThumbupRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type IsThumbupResponse struct {
	HasLiked bool  `json:"has_liked"`
	LikeNum  int64 `json:"like_num"`
}

type ListSessionsResponse struct {
	Sessions []SessionItem `json:"sessions"`
}

type LoginRequest struct {
	Mobile           string `json:"mobile"`
	VerificationCode string `json:"verification_code,optional"`
	Password         string `json:"password,optional"`
}

type LoginResponse struct {
	UserId int64 `json:"userId"`
	Token  Token `json:"token"`
}

type MarkAllReadRequest struct {
}

type MarkAllReadResponse struct {
}

type MarkReadRequest struct {
	Id int64 `json:"id"`
}

type MarkReadResponse struct {
}

type MemberInfoRequest struct {
}

type MemberInfoResponse struct {
	UserId      int64 `json:"user_id"`
	MemberLevel int32 `json:"member_level"`
	ExpireAt    int64 `json:"expire_at"`
	IsActive    bool  `json:"is_active"`
	RemainDays  int64 `json:"remain_days"`
}

type MemberOrderItem struct {
	OrderId        string  `json:"order_id"`
	UserId         int64   `json:"user_id"`
	TargetLevel    int32   `json:"target_level"`
	DurationMonths int32   `json:"duration_months"`
	Amount         float64 `json:"amount"`
	PayStatus      int32   `json:"pay_status"`
	PayChannel     string  `json:"pay_channel"`
	CreateTime     int64   `json:"create_time"`
	PayTime        int64   `json:"pay_time"`
}

type MemberOrderListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type MemberOrderListResponse struct {
	Items  []*MemberOrderItem `json:"items"`
	Cursor int64              `json:"cursor"`
	IsEnd  bool               `json:"is_end"`
}

type MemberRightItem struct {
	Id          int64  `json:"id"`
	Level       int32  `json:"level"`
	RightCode   string `json:"right_code"`
	RightName   string `json:"right_name"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

type MemberRightRequest struct {
	RightKey string `form:"right_key,optional"`
}

type MemberRightResponse struct {
	HasRight bool               `json:"has_right"`
	Level    int32              `json:"level"`
	Rights   []*MemberRightItem `json:"rights,optional"`
}

type MessageItem struct {
	Id             int64  `json:"id"`
	ConversationId int64  `json:"conversation_id"`
	SenderId       int64  `json:"sender_id"`
	ReceiverId     int64  `json:"receiver_id"`
	Content        string `json:"content"`
	MsgType        int32  `json:"msg_type"`
	IsRead         bool   `json:"is_read"`
	CreateTime     int64  `json:"create_time"`
}

type MessageResponse struct {
	Id             int64  `json:"id"`
	ConversationId int64  `json:"conversation_id"`
	SenderId       int64  `json:"sender_id"`
	ReceiverId     int64  `json:"receiver_id"`
	Content        string `json:"content"`
	MsgType        int32  `json:"msg_type"`
	CreateTime     int64  `json:"create_time"`
}

type MessagesRequest struct {
	ConversationId int64 `form:"conversation_id"`
	Cursor         int64 `form:"cursor"`
	PageSize       int64 `form:"page_size"`
}

type MessagesResponse struct {
	Items  []*MessageItem `json:"items"`
	Cursor int64          `json:"cursor"`
	IsEnd  bool           `json:"is_end"`
}

type NotificationItem struct {
	Id           int64  `json:"id"`
	UserId       int64  `json:"user_id"`
	SenderId     int64  `json:"sender_id"`
	SenderName   string `json:"sender_name"`
	SenderAvatar string `json:"sender_avatar"`
	MsgType      int32  `json:"msg_type"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	BizId        string `json:"biz_id"`
	ObjId        int64  `json:"obj_id"`
	IsRead       bool   `json:"is_read"`
	CreateTime   int64  `json:"create_time"`
}

type NotificationListRequest struct {
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
}

type NotificationListResponse struct {
	Items  []*NotificationItem `json:"items"`
	Cursor int64               `json:"cursor"`
	IsEnd  bool                `json:"is_end"`
}

type NotificationMsg struct {
	UserId        int64  `json:"user_id"`
	Type          int32  `json:"type"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	RefId         int64  `json:"ref_id"`
	BizId         string `json:"biz_id"`
	TriggerUserId int64  `json:"trigger_user_id"`
}

type NotificationRequest struct {
	Type     int32 `form:"type,optional"`
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type NotificationResponse struct {
	Items  []*NotificationItem `json:"items"`
	Cursor int64               `json:"cursor"`
	IsEnd  bool                `json:"is_end"`
}

type PublishQuestionRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	TagIds  string `json:"tag_ids"`
}

type PublishQuestionResponse struct {
	QuestionId int64 `json:"question_id"`
}

type PublishRequest struct {
	Title       string  `json:"title"`
	Content     string  `json:"content"`
	Description string  `json:"description"`
	Cover       string  `json:"cover"`
	TagIds      []int64 `json:"tag_ids,optional"`
}

type PublishResponse struct {
	ArticleId int64 `json:"article_id"`
}

type QueryOrderStatusReq struct {
	OrderSn string `json:"order_sn"`
}

type QueryOrderStatusResp struct {
	OrderSn     string `json:"order_sn"`
	Status      int32  `json:"status"`
	StatusText  string `json:"status_text"`
	TradeNo     string `json:"trade_no,optional"`
	TotalAmount string `json:"total_amount,optional"`
}

type QuestionDeleteRequest struct {
	QuestionId int64 `json:"question_id"`
}

type QuestionDetailRequest struct {
	QuestionId int64 `form:"question_id"`
}

type QuestionDetailResponse struct {
	Question *QuestionItem `json:"question"`
}

type QuestionItem struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	AuthorId   int64  `json:"author_id"`
	AnswerNum  int64  `json:"answer_num"`
	ViewNum    int64  `json:"view_num"`
	TagIds     string `json:"tag_ids"`
	CreateTime int64  `json:"create_time"`
}

type QuestionListRequest struct {
	AuthorId int64 `form:"author_id,optional"`
	Cursor   int64 `form:"cursor"`
	PageSize int64 `form:"page_size"`
	SortType int32 `form:"sort_type,optional"`
}

type QuestionListResponse struct {
	Items  []*QuestionItem `json:"items"`
	Cursor int64           `json:"cursor"`
	IsEnd  bool            `json:"is_end"`
}

type RegisterRequest struct {
	Name             string `json:"name"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verification_code"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type ReplyCountRequest struct {
	BizId string `form:"biz_id"`
	ObjId int64  `form:"obj_id"`
}

type ReplyCountResponse struct {
	Count int64 `json:"count"`
}

type ReplyCreateRequest struct {
	BizId    string `json:"biz_id"`
	ObjId    int64  `json:"obj_id"`
	Content  string `json:"content"`
	ParentId int64  `json:"parent_id,optional"`
}

type ReplyCreateResponse struct {
	Id int64 `json:"id"`
}

type ReplyDeleteRequest struct {
	Id int64 `json:"id"`
}

type ReplyDeleteResponse struct {
}

type ReplyDetailRequest struct {
	Id int64 `form:"id"`
}

type ReplyDetailResponse struct {
	Reply *ReplyItem `json:"reply"`
}

type ReplyItem struct {
	Id         int64        `json:"id"`
	BizId      string       `json:"biz_id"`
	ObjId      int64        `json:"obj_id"`
	UserId     int64        `json:"user_id"`
	Username   string       `json:"username"`
	Avatar     string       `json:"avatar"`
	Content    string       `json:"content"`
	ParentId   int64        `json:"parent_id"`
	LikeNum    int64        `json:"like_num"`
	SubReplies []*ReplyItem `json:"sub_replies"`
	CreateTime int64        `json:"create_time"`
}

type ReplyListRequest struct {
	BizId    string `form:"biz_id"`
	ObjId    int64  `form:"obj_id"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type ReplyListResponse struct {
	Items  []*ReplyItem `json:"items"`
	Cursor int64        `json:"cursor"`
	IsEnd  bool         `json:"is_end"`
}

type ResourcesByTagRequest struct {
	TagId        int64  `form:"tag_id"`
	ResourceType string `form:"resource_type,optional"`
	Cursor       int64  `form:"cursor"`
	PageSize     int64  `form:"page_size"`
}

type ResourcesByTagResponse struct {
	ResourceIds []int64 `json:"resource_ids"`
	Cursor      int64   `json:"cursor"`
	IsEnd       bool    `json:"is_end"`
}

type SearchInfo struct {
	ArticleId    int64  `json:"article_id"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	Cover        string `json:"cover"`
	AuthorId     int64  `json:"author_id"`
	AuthorName   string `json:"author_name"`
	LikeNum      int64  `json:"like_num"`
	CommentNum   int64  `json:"comment_num"`
	PublishTime  string `json:"publish_time"`
	AuthorAvatar string `json:"author_avatar"`
}

type SearchQuestionItem struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	AuthorId   int64  `json:"author_id"`
	AnswerNum  int64  `json:"answer_num"`
	TagIds     string `json:"tag_ids"`
	CreateTime int64  `json:"create_time"`
}

type SearchQuestionsRequest struct {
	Keyword  string `form:"keyword"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type SearchQuestionsResponse struct {
	Items  []*SearchQuestionItem `json:"items"`
	Cursor int64                 `json:"cursor"`
	IsEnd  bool                  `json:"is_end"`
}

type SearchRequest struct {
	Keyword  string `form:"keyword"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type SearchResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type SendMessageRequest struct {
	ReceiverId int64  `json:"receiver_id"`
	Content    string `json:"content"`
	MsgType    int32  `json:"msg_type"`
}

type SendMessageResponse struct {
}

type SessionItem struct {
	SessionID    string `json:"session_id"`
	Title        string `json:"title"`
	MessageCount int32  `json:"message_count"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type StopRequest struct {
	SessionID string `json:"session_id"`
}

type TagCreateRequest struct {
	Name        string `json:"name"`
	Category    string `json:"category"`
	Description string `json:"description,optional"`
	Icon        string `json:"icon,optional"`
}

type TagCreateResponse struct {
	Id int64 `json:"id"`
}

type TagDeleteRequest struct {
	Id int64 `json:"id"`
}

type TagDeleteResponse struct {
}

type TagDetailRequest struct {
	Id int64 `form:"id"`
}

type TagDetailResponse struct {
	Tag *TagItem `json:"tag"`
}

type TagItem struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	UseCount    int64  `json:"use_count"`
	FollowCount int64  `json:"follow_count"`
	IsFollowed  bool   `json:"is_followed"`
}

type TagListRequest struct {
	Category string `form:"category,optional"`
	Keyword  string `form:"keyword,optional"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type TagListResponse struct {
	Items  []*TagItem `json:"items"`
	Cursor int64      `json:"cursor"`
	IsEnd  bool       `json:"is_end"`
}

type TagResourceRequest struct {
	ResourceType string  `json:"resource_type"`
	ResourceId   int64   `json:"resource_id"`
	TagIds       []int64 `json:"tag_ids"`
}

type TagResourceResponse struct {
}

type TagUpdateRequest struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Category    string `json:"category,optional"`
	Description string `json:"description,optional"`
	Icon        string `json:"icon,optional"`
}

type TagUpdateResponse struct {
}

type TagsByResourceRequest struct {
	ResourceType string `form:"resource_type"`
	ResourceId   int64  `form:"resource_id"`
}

type TagsByResourceResponse struct {
	Tags []*TagItem `json:"tags"`
}

type ThumbupRequest struct {
	BizId    string `json:"biz_id"`
	ObjId    int64  `json:"obj_id"`
	LikeType int32  `json:"like_type"`
}

type ThumbupResponse struct {
	BizId     string `json:"biz_id"`
	ObjId     int64  `json:"obj_id"`
	LikeNum   int64  `json:"like_num"`
	HasLikded bool   `json:"has_liked"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UnFollowRequest struct {
	FollowId int64 `json:"follow_id"`
}

type UnFollowResponse struct {
}

type UnreadCountRequest struct {
}

type UnreadCountResponse struct {
	Count int64 `json:"count"`
}

type UntagResourceRequest struct {
	ResourceType string  `json:"resource_type"`
	ResourceId   int64   `json:"resource_id"`
	TagIds       []int64 `json:"tag_ids"`
}

type UntagResourceResponse struct {
}

type UpdateProfileRequest struct {
	Username     string `json:"username,optional"`
	Avatar       string `json:"avatar,optional"`
	Bio          string `json:"bio,optional"`
	Gender       int32  `json:"gender,optional"`
	ProfileCover string `json:"profile_cover,optional"`
}

type UpdateProfileResponse struct {
}

type UpgradeMemberRequest struct {
	Level         int32  `json:"level"`
	DurationDays  int32  `json:"duration_days"`
	TransactionId string `json:"transaction_id,optional"`
	Amount        int64  `json:"amount,optional"`
	PayChannel    string `json:"pay_channel,optional"`
}

type UpgradeMemberResponse struct {
}

type UploadCoverResponse struct {
	CoverUrl string `json:"cover_url"`
}

type UploadTokenRequest struct {
	FileType string `json:"file_type"`
	Scene    string `json:"scene,optional"`
}

type UploadTokenResponse struct {
	UploadUrl   string `json:"upload_url"`
	DownloadUrl string `json:"download_url"`
	ObjectKey   string `json:"object_key"`
	ExpiresIn   int64  `json:"expires_in"`
}

type UserInfoResponse struct {
	UserId       int64  `json:"user_id"`
	Username     string `json:"username"`
	Avatar       string `json:"avatar"`
	Role         int64  `json:"role"`
	DisplayId    string `json:"display_id"`
	Bio          string `json:"bio"`
	Gender       int32  `json:"gender"`
	ProfileCover string `json:"profile_cover"`
}

type UserProfileRequest struct {
	UserId int64 `form:"user_id,optional"`
}

type UserProfileResponse struct {
	UserId       int64  `json:"user_id"`
	Username     string `json:"username"`
	Avatar       string `json:"avatar"`
	Role         int64  `json:"role"`
	DisplayId    string `json:"display_id"`
	Bio          string `json:"bio"`
	Gender       int32  `json:"gender"`
	ProfileCover string `json:"profile_cover"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}

type VideoPartItem struct {
	PartNumber int    `json:"partNumber"`
	ETag       string `json:"eTag"`
}

type VideoStatusRequest struct {
	VideoId int64 `form:"videoId"`
}

type VideoStatusResponse struct {
	VideoId  int64  `json:"videoId"`
	Status   string `json:"status"`
	VideoUrl string `json:"videoUrl"`
	CoverUrl string `json:"coverUrl"`
	Duration int64  `json:"duration"`
	Width    int    `json:"width"`
	Height   int    `json:"height"`
	ErrMsg   string `json:"errMsg,optional"`
}

type VideoUploadCompleteRequest struct {
	VideoId   int64           `json:"videoId"`
	UploadId  string          `json:"uploadId"`
	ObjectKey string          `json:"objectKey"`
	Parts     []VideoPartItem `json:"parts"`
	FileHash  string          `json:"fileHash,optional"`
}

type VideoUploadCompleteResponse struct {
	VideoId  int64  `json:"videoId"`
	Status   string `json:"status"`
	VideoUrl string `json:"videoUrl"`
}

type VideoUploadInitRequest struct {
	FileName string `json:"fileName"`
	FileSize int64  `json:"fileSize"`
	FileType string `json:"fileType"`
	PartSize int64  `json:"partSize,optional"`
	FileHash string `json:"fileHash,optional"`
}

type VideoUploadInitResponse struct {
	VideoId       int64    `json:"videoId"`
	UploadId      string   `json:"uploadId"`
	ObjectKey     string   `json:"objectKey"`
	PartUrls      []string `json:"partUrls"`
	PartSize      int64    `json:"partSize"`
	PartCount     int      `json:"partCount"`
	ExpireSec     int64    `json:"expireSec"`
	IsQuickDone   bool     `json:"isQuickDone,optional"`
	UploadedParts []int    `json:"uploadedParts,optional"`
}

type WsInMessage struct {
	Type        string `json:"type"`
	ReceiverId  int64  `json:"receiver_id,omitempty"`
	Content     string `json:"content,omitempty"`
	MsgType     int32  `json:"msg_type,omitempty"`
	ClientMsgId string `json:"client_msg_id,omitempty"`
}

type WsOutMessage struct {
	Type        string `json:"type"`
	SenderId    int64  `json:"sender_id,omitempty"`
	Content     string `json:"content,omitempty"`
	MsgType     int32  `json:"msg_type,omitempty"`
	CreateTime  int64  `json:"create_time,omitempty"`
	Message     string `json:"message,omitempty"`
	ClientMsgId string `json:"client_msg_id,omitempty"`
}
