// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: reply.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	ReplyUserId   int64                  `protobuf:"varint,3,opt,name=replyUserId,proto3" json:"replyUserId,omitempty"`
	BeReplyUserId int64                  `protobuf:"varint,4,opt,name=beReplyUserId,proto3" json:"beReplyUserId,omitempty"`
	ParentId      int64                  `protobuf:"varint,5,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyRequest) Reset() {
	*x = CreateReplyRequest{}
	mi := &file_reply_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyRequest) ProtoMessage() {}

func (x *CreateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReplyRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *CreateReplyRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CreateReplyRequest) GetReplyUserId() int64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *CreateReplyRequest) GetBeReplyUserId() int64 {
	if x != nil {
		return x.BeReplyUserId
	}
	return 0
}

func (x *CreateReplyRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateReplyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyData) Reset() {
	*x = CreateReplyData{}
	mi := &file_reply_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyData) ProtoMessage() {}

func (x *CreateReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyData.ProtoReflect.Descriptor instead.
func (*CreateReplyData) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReplyData) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

type CreateReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CreateReplyData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyResponse) Reset() {
	*x = CreateReplyResponse{}
	mi := &file_reply_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyResponse) ProtoMessage() {}

func (x *CreateReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyResponse.ProtoReflect.Descriptor instead.
func (*CreateReplyResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReplyResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateReplyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateReplyResponse) GetData() *CreateReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyRequest) Reset() {
	*x = DeleteReplyRequest{}
	mi := &file_reply_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyRequest) ProtoMessage() {}

func (x *DeleteReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReplyRequest) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *DeleteReplyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteReplyRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type DeleteReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyResponse) Reset() {
	*x = DeleteReplyResponse{}
	mi := &file_reply_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyResponse) ProtoMessage() {}

func (x *DeleteReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyResponse.ProtoReflect.Descriptor instead.
func (*DeleteReplyResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReplyResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteReplyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ReplyDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyDetailRequest) Reset() {
	*x = ReplyDetailRequest{}
	mi := &file_reply_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyDetailRequest) ProtoMessage() {}

func (x *ReplyDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyDetailRequest.ProtoReflect.Descriptor instead.
func (*ReplyDetailRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyDetailRequest) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

type ReplyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	ReplyUserId   int64                  `protobuf:"varint,4,opt,name=replyUserId,proto3" json:"replyUserId,omitempty"`
	BeReplyUserId int64                  `protobuf:"varint,5,opt,name=beReplyUserId,proto3" json:"beReplyUserId,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	LikeNum       int64                  `protobuf:"varint,8,opt,name=likeNum,proto3" json:"likeNum,omitempty"`
	CreateTime    int64                  `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	SubReplies    []*ReplyItem           `protobuf:"bytes,10,rep,name=subReplies,proto3" json:"subReplies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyItem) Reset() {
	*x = ReplyItem{}
	mi := &file_reply_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyItem) ProtoMessage() {}

func (x *ReplyItem) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyItem.ProtoReflect.Descriptor instead.
func (*ReplyItem) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyItem) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *ReplyItem) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ReplyItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReplyItem) GetReplyUserId() int64 {
	if x != nil {
		return x.ReplyUserId
	}
	return 0
}

func (x *ReplyItem) GetBeReplyUserId() int64 {
	if x != nil {
		return x.BeReplyUserId
	}
	return 0
}

func (x *ReplyItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ReplyItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyItem) GetLikeNum() int64 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *ReplyItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ReplyItem) GetSubReplies() []*ReplyItem {
	if x != nil {
		return x.SubReplies
	}
	return nil
}

type ReplyDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ReplyItem             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyDetailResponse) Reset() {
	*x = ReplyDetailResponse{}
	mi := &file_reply_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyDetailResponse) ProtoMessage() {}

func (x *ReplyDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyDetailResponse.ProtoReflect.Descriptor instead.
func (*ReplyDetailResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyDetailResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReplyDetailResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReplyDetailResponse) GetData() *ReplyItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SortType      int32                  `protobuf:"varint,5,opt,name=sortType,proto3" json:"sortType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyListRequest) Reset() {
	*x = ReplyListRequest{}
	mi := &file_reply_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyListRequest) ProtoMessage() {}

func (x *ReplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyListRequest.ProtoReflect.Descriptor instead.
func (*ReplyListRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyListRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ReplyListRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ReplyListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ReplyListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReplyListRequest) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

type ReplyListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ReplyItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyListData) Reset() {
	*x = ReplyListData{}
	mi := &file_reply_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyListData) ProtoMessage() {}

func (x *ReplyListData) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyListData.ProtoReflect.Descriptor instead.
func (*ReplyListData) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{9}
}

func (x *ReplyListData) GetItems() []*ReplyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReplyListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ReplyListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type ReplyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ReplyListData         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyListResponse) Reset() {
	*x = ReplyListResponse{}
	mi := &file_reply_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyListResponse) ProtoMessage() {}

func (x *ReplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyListResponse.ProtoReflect.Descriptor instead.
func (*ReplyListResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{10}
}

func (x *ReplyListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReplyListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReplyListResponse) GetData() *ReplyListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReplyCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCountRequest) Reset() {
	*x = ReplyCountRequest{}
	mi := &file_reply_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCountRequest) ProtoMessage() {}

func (x *ReplyCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCountRequest.ProtoReflect.Descriptor instead.
func (*ReplyCountRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{11}
}

func (x *ReplyCountRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ReplyCountRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type ReplyCountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyNum      int64                  `protobuf:"varint,1,opt,name=replyNum,proto3" json:"replyNum,omitempty"`
	ReplyRootNum  int64                  `protobuf:"varint,2,opt,name=replyRootNum,proto3" json:"replyRootNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCountData) Reset() {
	*x = ReplyCountData{}
	mi := &file_reply_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCountData) ProtoMessage() {}

func (x *ReplyCountData) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCountData.ProtoReflect.Descriptor instead.
func (*ReplyCountData) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{12}
}

func (x *ReplyCountData) GetReplyNum() int64 {
	if x != nil {
		return x.ReplyNum
	}
	return 0
}

func (x *ReplyCountData) GetReplyRootNum() int64 {
	if x != nil {
		return x.ReplyRootNum
	}
	return 0
}

type ReplyCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ReplyCountData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCountResponse) Reset() {
	*x = ReplyCountResponse{}
	mi := &file_reply_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCountResponse) ProtoMessage() {}

func (x *ReplyCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCountResponse.ProtoReflect.Descriptor instead.
func (*ReplyCountResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyCountResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReplyCountResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReplyCountResponse) GetData() *ReplyCountData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdminReplyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminReplyListRequest) Reset() {
	*x = AdminReplyListRequest{}
	mi := &file_reply_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminReplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReplyListRequest) ProtoMessage() {}

func (x *AdminReplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReplyListRequest.ProtoReflect.Descriptor instead.
func (*AdminReplyListRequest) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{14}
}

func (x *AdminReplyListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AdminReplyListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *AdminReplyListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminReplyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ReplyListData         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminReplyListResponse) Reset() {
	*x = AdminReplyListResponse{}
	mi := &file_reply_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminReplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReplyListResponse) ProtoMessage() {}

func (x *AdminReplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reply_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReplyListResponse.ProtoReflect.Descriptor instead.
func (*AdminReplyListResponse) Descriptor() ([]byte, []int) {
	return file_reply_proto_rawDescGZIP(), []int{15}
}

func (x *AdminReplyListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminReplyListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AdminReplyListResponse) GetData() *ReplyListData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_reply_proto protoreflect.FileDescriptor

const file_reply_proto_rawDesc = "" +
	"\n" +
	"\vreply.proto\x12\x06social\"\xc4\x01\n" +
	"\x12CreateReplyRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\x12 \n" +
	"\vreplyUserId\x18\x03 \x01(\x03R\vreplyUserId\x12$\n" +
	"\rbeReplyUserId\x18\x04 \x01(\x03R\rbeReplyUserId\x12\x1a\n" +
	"\bparentId\x18\x05 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"+\n" +
	"\x0fCreateReplyData\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\"h\n" +
	"\x13CreateReplyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.social.CreateReplyDataR\x04data\"`\n" +
	"\x12DeleteReplyRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\aisAdmin\x18\x03 \x01(\bR\aisAdmin\";\n" +
	"\x13DeleteReplyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\".\n" +
	"\x12ReplyDetailRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\"\xc2\x02\n" +
	"\tReplyItem\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x03R\areplyId\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\x03R\btargetId\x12 \n" +
	"\vreplyUserId\x18\x04 \x01(\x03R\vreplyUserId\x12$\n" +
	"\rbeReplyUserId\x18\x05 \x01(\x03R\rbeReplyUserId\x12\x1a\n" +
	"\bparentId\x18\x06 \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x18\n" +
	"\alikeNum\x18\b \x01(\x03R\alikeNum\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\x03R\n" +
	"createTime\x121\n" +
	"\n" +
	"subReplies\x18\n" +
	" \x03(\v2\x11.social.ReplyItemR\n" +
	"subReplies\"b\n" +
	"\x13ReplyDetailResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12%\n" +
	"\x04data\x18\x03 \x01(\v2\x11.social.ReplyItemR\x04data\"\x94\x01\n" +
	"\x10ReplyListRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bsortType\x18\x05 \x01(\x05R\bsortType\"f\n" +
	"\rReplyListData\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.social.ReplyItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"d\n" +
	"\x11ReplyListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.social.ReplyListDataR\x04data\"E\n" +
	"\x11ReplyCountRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\"P\n" +
	"\x0eReplyCountData\x12\x1a\n" +
	"\breplyNum\x18\x01 \x01(\x03R\breplyNum\x12\"\n" +
	"\freplyRootNum\x18\x02 \x01(\x03R\freplyRootNum\"f\n" +
	"\x12ReplyCountResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.social.ReplyCountDataR\x04data\"e\n" +
	"\x15AdminReplyListRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"i\n" +
	"\x16AdminReplyListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.social.ReplyListDataR\x04data2\xb7\x03\n" +
	"\x05Reply\x12F\n" +
	"\vCreateReply\x12\x1a.social.CreateReplyRequest\x1a\x1b.social.CreateReplyResponse\x12F\n" +
	"\vDeleteReply\x12\x1a.social.DeleteReplyRequest\x1a\x1b.social.DeleteReplyResponse\x12F\n" +
	"\vReplyDetail\x12\x1a.social.ReplyDetailRequest\x1a\x1b.social.ReplyDetailResponse\x12@\n" +
	"\tReplyList\x12\x18.social.ReplyListRequest\x1a\x19.social.ReplyListResponse\x12C\n" +
	"\n" +
	"ReplyCount\x12\x19.social.ReplyCountRequest\x1a\x1a.social.ReplyCountResponse\x12O\n" +
	"\x0eAdminReplyList\x12\x1d.social.AdminReplyListRequest\x1a\x1e.social.AdminReplyListResponseB\"Z api-thinktalk/client/reply/pb;pbb\x06proto3"

var (
	file_reply_proto_rawDescOnce sync.Once
	file_reply_proto_rawDescData []byte
)

func file_reply_proto_rawDescGZIP() []byte {
	file_reply_proto_rawDescOnce.Do(func() {
		file_reply_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reply_proto_rawDesc), len(file_reply_proto_rawDesc)))
	})
	return file_reply_proto_rawDescData
}

var file_reply_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_reply_proto_goTypes = []any{
	(*CreateReplyRequest)(nil),     // 0: social.CreateReplyRequest
	(*CreateReplyData)(nil),        // 1: social.CreateReplyData
	(*CreateReplyResponse)(nil),    // 2: social.CreateReplyResponse
	(*DeleteReplyRequest)(nil),     // 3: social.DeleteReplyRequest
	(*DeleteReplyResponse)(nil),    // 4: social.DeleteReplyResponse
	(*ReplyDetailRequest)(nil),     // 5: social.ReplyDetailRequest
	(*ReplyItem)(nil),              // 6: social.ReplyItem
	(*ReplyDetailResponse)(nil),    // 7: social.ReplyDetailResponse
	(*ReplyListRequest)(nil),       // 8: social.ReplyListRequest
	(*ReplyListData)(nil),          // 9: social.ReplyListData
	(*ReplyListResponse)(nil),      // 10: social.ReplyListResponse
	(*ReplyCountRequest)(nil),      // 11: social.ReplyCountRequest
	(*ReplyCountData)(nil),         // 12: social.ReplyCountData
	(*ReplyCountResponse)(nil),     // 13: social.ReplyCountResponse
	(*AdminReplyListRequest)(nil),  // 14: social.AdminReplyListRequest
	(*AdminReplyListResponse)(nil), // 15: social.AdminReplyListResponse
}
var file_reply_proto_depIdxs = []int32{
	1,  // 0: social.CreateReplyResponse.data:type_name -> social.CreateReplyData
	6,  // 1: social.ReplyItem.subReplies:type_name -> social.ReplyItem
	6,  // 2: social.ReplyDetailResponse.data:type_name -> social.ReplyItem
	6,  // 3: social.ReplyListData.items:type_name -> social.ReplyItem
	9,  // 4: social.ReplyListResponse.data:type_name -> social.ReplyListData
	12, // 5: social.ReplyCountResponse.data:type_name -> social.ReplyCountData
	9,  // 6: social.AdminReplyListResponse.data:type_name -> social.ReplyListData
	0,  // 7: social.Reply.CreateReply:input_type -> social.CreateReplyRequest
	3,  // 8: social.Reply.DeleteReply:input_type -> social.DeleteReplyRequest
	5,  // 9: social.Reply.ReplyDetail:input_type -> social.ReplyDetailRequest
	8,  // 10: social.Reply.ReplyList:input_type -> social.ReplyListRequest
	11, // 11: social.Reply.ReplyCount:input_type -> social.ReplyCountRequest
	14, // 12: social.Reply.AdminReplyList:input_type -> social.AdminReplyListRequest
	2,  // 13: social.Reply.CreateReply:output_type -> social.CreateReplyResponse
	4,  // 14: social.Reply.DeleteReply:output_type -> social.DeleteReplyResponse
	7,  // 15: social.Reply.ReplyDetail:output_type -> social.ReplyDetailResponse
	10, // 16: social.Reply.ReplyList:output_type -> social.ReplyListResponse
	13, // 17: social.Reply.ReplyCount:output_type -> social.ReplyCountResponse
	15, // 18: social.Reply.AdminReplyList:output_type -> social.AdminReplyListResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_reply_proto_init() }
func file_reply_proto_init() {
	if File_reply_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reply_proto_rawDesc), len(file_reply_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reply_proto_goTypes,
		DependencyIndexes: file_reply_proto_depIdxs,
		MessageInfos:      file_reply_proto_msgTypes,
	}.Build()
	File_reply_proto = out.File
	file_reply_proto_goTypes = nil
	file_reply_proto_depIdxs = nil
}
