// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: concerned.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddConcernedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConcernedRequest) Reset() {
	*x = AddConcernedRequest{}
	mi := &file_concerned_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConcernedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConcernedRequest) ProtoMessage() {}

func (x *AddConcernedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConcernedRequest.ProtoReflect.Descriptor instead.
func (*AddConcernedRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{0}
}

func (x *AddConcernedRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *AddConcernedRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *AddConcernedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddConcernedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConcernedResponse) Reset() {
	*x = AddConcernedResponse{}
	mi := &file_concerned_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConcernedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConcernedResponse) ProtoMessage() {}

func (x *AddConcernedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConcernedResponse.ProtoReflect.Descriptor instead.
func (*AddConcernedResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{1}
}

func (x *AddConcernedResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddConcernedResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CancelConcernedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelConcernedRequest) Reset() {
	*x = CancelConcernedRequest{}
	mi := &file_concerned_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConcernedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConcernedRequest) ProtoMessage() {}

func (x *CancelConcernedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConcernedRequest.ProtoReflect.Descriptor instead.
func (*CancelConcernedRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{2}
}

func (x *CancelConcernedRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *CancelConcernedRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *CancelConcernedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelConcernedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelConcernedResponse) Reset() {
	*x = CancelConcernedResponse{}
	mi := &file_concerned_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConcernedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConcernedResponse) ProtoMessage() {}

func (x *CancelConcernedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConcernedResponse.ProtoReflect.Descriptor instead.
func (*CancelConcernedResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{3}
}

func (x *CancelConcernedResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelConcernedResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IsConcernedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConcernedRequest) Reset() {
	*x = IsConcernedRequest{}
	mi := &file_concerned_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConcernedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConcernedRequest) ProtoMessage() {}

func (x *IsConcernedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConcernedRequest.ProtoReflect.Descriptor instead.
func (*IsConcernedRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{4}
}

func (x *IsConcernedRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *IsConcernedRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *IsConcernedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsConcernedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsConcerned   bool                   `protobuf:"varint,1,opt,name=isConcerned,proto3" json:"isConcerned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConcernedData) Reset() {
	*x = IsConcernedData{}
	mi := &file_concerned_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConcernedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConcernedData) ProtoMessage() {}

func (x *IsConcernedData) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConcernedData.ProtoReflect.Descriptor instead.
func (*IsConcernedData) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{5}
}

func (x *IsConcernedData) GetIsConcerned() bool {
	if x != nil {
		return x.IsConcerned
	}
	return false
}

type IsConcernedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *IsConcernedData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConcernedResponse) Reset() {
	*x = IsConcernedResponse{}
	mi := &file_concerned_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConcernedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConcernedResponse) ProtoMessage() {}

func (x *IsConcernedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConcernedResponse.ProtoReflect.Descriptor instead.
func (*IsConcernedResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{6}
}

func (x *IsConcernedResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IsConcernedResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *IsConcernedResponse) GetData() *IsConcernedData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConcernedListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedListRequest) Reset() {
	*x = ConcernedListRequest{}
	mi := &file_concerned_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedListRequest) ProtoMessage() {}

func (x *ConcernedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedListRequest.ProtoReflect.Descriptor instead.
func (*ConcernedListRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{7}
}

func (x *ConcernedListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConcernedListRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ConcernedListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ConcernedListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ConcernedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BizId         string                 `protobuf:"bytes,2,opt,name=bizId,proto3" json:"bizId,omitempty"`
	ObjId         int64                  `protobuf:"varint,3,opt,name=objId,proto3" json:"objId,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedItem) Reset() {
	*x = ConcernedItem{}
	mi := &file_concerned_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedItem) ProtoMessage() {}

func (x *ConcernedItem) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedItem.ProtoReflect.Descriptor instead.
func (*ConcernedItem) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{8}
}

func (x *ConcernedItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConcernedItem) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ConcernedItem) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *ConcernedItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ConcernedListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConcernedItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedListData) Reset() {
	*x = ConcernedListData{}
	mi := &file_concerned_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedListData) ProtoMessage() {}

func (x *ConcernedListData) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedListData.ProtoReflect.Descriptor instead.
func (*ConcernedListData) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{9}
}

func (x *ConcernedListData) GetItems() []*ConcernedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ConcernedListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ConcernedListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type ConcernedListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ConcernedListData     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedListResponse) Reset() {
	*x = ConcernedListResponse{}
	mi := &file_concerned_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedListResponse) ProtoMessage() {}

func (x *ConcernedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedListResponse.ProtoReflect.Descriptor instead.
func (*ConcernedListResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{10}
}

func (x *ConcernedListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConcernedListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConcernedListResponse) GetData() *ConcernedListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConcernedCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedCountRequest) Reset() {
	*x = ConcernedCountRequest{}
	mi := &file_concerned_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedCountRequest) ProtoMessage() {}

func (x *ConcernedCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedCountRequest.ProtoReflect.Descriptor instead.
func (*ConcernedCountRequest) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{11}
}

func (x *ConcernedCountRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ConcernedCountRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

type ConcernedCountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConcernedNum  int64                  `protobuf:"varint,1,opt,name=concernedNum,proto3" json:"concernedNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedCountData) Reset() {
	*x = ConcernedCountData{}
	mi := &file_concerned_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedCountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedCountData) ProtoMessage() {}

func (x *ConcernedCountData) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedCountData.ProtoReflect.Descriptor instead.
func (*ConcernedCountData) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{12}
}

func (x *ConcernedCountData) GetConcernedNum() int64 {
	if x != nil {
		return x.ConcernedNum
	}
	return 0
}

type ConcernedCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ConcernedCountData    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcernedCountResponse) Reset() {
	*x = ConcernedCountResponse{}
	mi := &file_concerned_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcernedCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcernedCountResponse) ProtoMessage() {}

func (x *ConcernedCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerned_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcernedCountResponse.ProtoReflect.Descriptor instead.
func (*ConcernedCountResponse) Descriptor() ([]byte, []int) {
	return file_concerned_proto_rawDescGZIP(), []int{13}
}

func (x *ConcernedCountResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConcernedCountResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConcernedCountResponse) GetData() *ConcernedCountData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_concerned_proto protoreflect.FileDescriptor

const file_concerned_proto_rawDesc = "" +
	"\n" +
	"\x0fconcerned.proto\x12\x06social\"Y\n" +
	"\x13AddConcernedRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"<\n" +
	"\x14AddConcernedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\\\n" +
	"\x16CancelConcernedRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"?\n" +
	"\x17CancelConcernedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"X\n" +
	"\x12IsConcernedRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"3\n" +
	"\x0fIsConcernedData\x12 \n" +
	"\visConcerned\x18\x01 \x01(\bR\visConcerned\"h\n" +
	"\x13IsConcernedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.social.IsConcernedDataR\x04data\"x\n" +
	"\x14ConcernedListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"k\n" +
	"\rConcernedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05bizId\x18\x02 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x03 \x01(\x03R\x05objId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\"n\n" +
	"\x11ConcernedListData\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.social.ConcernedItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"l\n" +
	"\x15ConcernedListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.social.ConcernedListDataR\x04data\"C\n" +
	"\x15ConcernedCountRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\"8\n" +
	"\x12ConcernedCountData\x12\"\n" +
	"\fconcernedNum\x18\x01 \x01(\x03R\fconcernedNum\"n\n" +
	"\x16ConcernedCountResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.social.ConcernedCountDataR\x04data2\x91\x03\n" +
	"\tConcerned\x12I\n" +
	"\fAddConcerned\x12\x1b.social.AddConcernedRequest\x1a\x1c.social.AddConcernedResponse\x12R\n" +
	"\x0fCancelConcerned\x12\x1e.social.CancelConcernedRequest\x1a\x1f.social.CancelConcernedResponse\x12F\n" +
	"\vIsConcerned\x12\x1a.social.IsConcernedRequest\x1a\x1b.social.IsConcernedResponse\x12L\n" +
	"\rConcernedList\x12\x1c.social.ConcernedListRequest\x1a\x1d.social.ConcernedListResponse\x12O\n" +
	"\x0eConcernedCount\x12\x1d.social.ConcernedCountRequest\x1a\x1e.social.ConcernedCountResponseB&Z$api-thinktalk/client/concerned/pb;pbb\x06proto3"

var (
	file_concerned_proto_rawDescOnce sync.Once
	file_concerned_proto_rawDescData []byte
)

func file_concerned_proto_rawDescGZIP() []byte {
	file_concerned_proto_rawDescOnce.Do(func() {
		file_concerned_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_concerned_proto_rawDesc), len(file_concerned_proto_rawDesc)))
	})
	return file_concerned_proto_rawDescData
}

var file_concerned_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_concerned_proto_goTypes = []any{
	(*AddConcernedRequest)(nil),     // 0: social.AddConcernedRequest
	(*AddConcernedResponse)(nil),    // 1: social.AddConcernedResponse
	(*CancelConcernedRequest)(nil),  // 2: social.CancelConcernedRequest
	(*CancelConcernedResponse)(nil), // 3: social.CancelConcernedResponse
	(*IsConcernedRequest)(nil),      // 4: social.IsConcernedRequest
	(*IsConcernedData)(nil),         // 5: social.IsConcernedData
	(*IsConcernedResponse)(nil),     // 6: social.IsConcernedResponse
	(*ConcernedListRequest)(nil),    // 7: social.ConcernedListRequest
	(*ConcernedItem)(nil),           // 8: social.ConcernedItem
	(*ConcernedListData)(nil),       // 9: social.ConcernedListData
	(*ConcernedListResponse)(nil),   // 10: social.ConcernedListResponse
	(*ConcernedCountRequest)(nil),   // 11: social.ConcernedCountRequest
	(*ConcernedCountData)(nil),      // 12: social.ConcernedCountData
	(*ConcernedCountResponse)(nil),  // 13: social.ConcernedCountResponse
}
var file_concerned_proto_depIdxs = []int32{
	5,  // 0: social.IsConcernedResponse.data:type_name -> social.IsConcernedData
	8,  // 1: social.ConcernedListData.items:type_name -> social.ConcernedItem
	9,  // 2: social.ConcernedListResponse.data:type_name -> social.ConcernedListData
	12, // 3: social.ConcernedCountResponse.data:type_name -> social.ConcernedCountData
	0,  // 4: social.Concerned.AddConcerned:input_type -> social.AddConcernedRequest
	2,  // 5: social.Concerned.CancelConcerned:input_type -> social.CancelConcernedRequest
	4,  // 6: social.Concerned.IsConcerned:input_type -> social.IsConcernedRequest
	7,  // 7: social.Concerned.ConcernedList:input_type -> social.ConcernedListRequest
	11, // 8: social.Concerned.ConcernedCount:input_type -> social.ConcernedCountRequest
	1,  // 9: social.Concerned.AddConcerned:output_type -> social.AddConcernedResponse
	3,  // 10: social.Concerned.CancelConcerned:output_type -> social.CancelConcernedResponse
	6,  // 11: social.Concerned.IsConcerned:output_type -> social.IsConcernedResponse
	10, // 12: social.Concerned.ConcernedList:output_type -> social.ConcernedListResponse
	13, // 13: social.Concerned.ConcernedCount:output_type -> social.ConcernedCountResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_concerned_proto_init() }
func file_concerned_proto_init() {
	if File_concerned_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_concerned_proto_rawDesc), len(file_concerned_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_concerned_proto_goTypes,
		DependencyIndexes: file_concerned_proto_depIdxs,
		MessageInfos:      file_concerned_proto_msgTypes,
	}.Build()
	File_concerned_proto = out.File
	file_concerned_proto_goTypes = nil
	file_concerned_proto_depIdxs = nil
}
