// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: member.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoRequest) Reset() {
	*x = MemberInfoRequest{}
	mi := &file_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoRequest) ProtoMessage() {}

func (x *MemberInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoRequest.ProtoReflect.Descriptor instead.
func (*MemberInfoRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MemberInfoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	LevelName     string                 `protobuf:"bytes,3,opt,name=levelName,proto3" json:"levelName,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoData) Reset() {
	*x = MemberInfoData{}
	mi := &file_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoData) ProtoMessage() {}

func (x *MemberInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoData.ProtoReflect.Descriptor instead.
func (*MemberInfoData) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberInfoData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberInfoData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MemberInfoData) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *MemberInfoData) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *MemberInfoData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MemberInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *MemberInfoData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoResponse) Reset() {
	*x = MemberInfoResponse{}
	mi := &file_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoResponse) ProtoMessage() {}

func (x *MemberInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoResponse.ProtoReflect.Descriptor instead.
func (*MemberInfoResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{2}
}

func (x *MemberInfoResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MemberInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MemberInfoResponse) GetData() *MemberInfoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpgradeMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,3,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	TransactionId string                 `protobuf:"bytes,4,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,6,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMemberRequest) Reset() {
	*x = UpgradeMemberRequest{}
	mi := &file_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMemberRequest) ProtoMessage() {}

func (x *UpgradeMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMemberRequest.ProtoReflect.Descriptor instead.
func (*UpgradeMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{3}
}

func (x *UpgradeMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradeMemberRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpgradeMemberRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpgradeMemberRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpgradeMemberRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpgradeMemberRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type UpgradeMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMemberResponse) Reset() {
	*x = UpgradeMemberResponse{}
	mi := &file_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMemberResponse) ProtoMessage() {}

func (x *UpgradeMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMemberResponse.ProtoReflect.Descriptor instead.
func (*UpgradeMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{4}
}

func (x *UpgradeMemberResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpgradeMemberResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CheckMemberRightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RightKey      string                 `protobuf:"bytes,2,opt,name=rightKey,proto3" json:"rightKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightRequest) Reset() {
	*x = CheckMemberRightRequest{}
	mi := &file_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightRequest) ProtoMessage() {}

func (x *CheckMemberRightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightRequest.ProtoReflect.Descriptor instead.
func (*CheckMemberRightRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{5}
}

func (x *CheckMemberRightRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckMemberRightRequest) GetRightKey() string {
	if x != nil {
		return x.RightKey
	}
	return ""
}

type CheckMemberRightData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasRight      bool                   `protobuf:"varint,1,opt,name=hasRight,proto3" json:"hasRight,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightData) Reset() {
	*x = CheckMemberRightData{}
	mi := &file_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightData) ProtoMessage() {}

func (x *CheckMemberRightData) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightData.ProtoReflect.Descriptor instead.
func (*CheckMemberRightData) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{6}
}

func (x *CheckMemberRightData) GetHasRight() bool {
	if x != nil {
		return x.HasRight
	}
	return false
}

func (x *CheckMemberRightData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type CheckMemberRightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CheckMemberRightData  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightResponse) Reset() {
	*x = CheckMemberRightResponse{}
	mi := &file_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightResponse) ProtoMessage() {}

func (x *CheckMemberRightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightResponse.ProtoReflect.Descriptor instead.
func (*CheckMemberRightResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{7}
}

func (x *CheckMemberRightResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckMemberRightResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CheckMemberRightResponse) GetData() *CheckMemberRightData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MemberOrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListRequest) Reset() {
	*x = MemberOrderListRequest{}
	mi := &file_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListRequest) ProtoMessage() {}

func (x *MemberOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListRequest.ProtoReflect.Descriptor instead.
func (*MemberOrderListRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{8}
}

func (x *MemberOrderListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberOrderListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MemberOrderListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MemberOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,4,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,6,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderItem) Reset() {
	*x = MemberOrderItem{}
	mi := &file_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderItem) ProtoMessage() {}

func (x *MemberOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderItem.ProtoReflect.Descriptor instead.
func (*MemberOrderItem) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{9}
}

func (x *MemberOrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberOrderItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberOrderItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MemberOrderItem) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *MemberOrderItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MemberOrderItem) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *MemberOrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberOrderItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type MemberOrderListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MemberOrderItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListData) Reset() {
	*x = MemberOrderListData{}
	mi := &file_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListData) ProtoMessage() {}

func (x *MemberOrderListData) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListData.ProtoReflect.Descriptor instead.
func (*MemberOrderListData) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{10}
}

func (x *MemberOrderListData) GetItems() []*MemberOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MemberOrderListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MemberOrderListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type MemberOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *MemberOrderListData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListResponse) Reset() {
	*x = MemberOrderListResponse{}
	mi := &file_member_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListResponse) ProtoMessage() {}

func (x *MemberOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListResponse.ProtoReflect.Descriptor instead.
func (*MemberOrderListResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{11}
}

func (x *MemberOrderListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MemberOrderListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MemberOrderListResponse) GetData() *MemberOrderListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,3,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,5,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_member_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateOrderRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CreateOrderRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type CreateOrderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderData) Reset() {
	*x = CreateOrderData{}
	mi := &file_member_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderData) ProtoMessage() {}

func (x *CreateOrderData) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderData.ProtoReflect.Descriptor instead.
func (*CreateOrderData) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrderData) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreateOrderData) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CreateOrderData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_member_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOrderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateOrderResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateOrderResponse) GetData() *CreateOrderData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PayCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackRequest) Reset() {
	*x = PayCallbackRequest{}
	mi := &file_member_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackRequest) ProtoMessage() {}

func (x *PayCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackRequest.ProtoReflect.Descriptor instead.
func (*PayCallbackRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{15}
}

func (x *PayCallbackRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PayCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PayCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackResponse) Reset() {
	*x = PayCallbackResponse{}
	mi := &file_member_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackResponse) ProtoMessage() {}

func (x *PayCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackResponse.ProtoReflect.Descriptor instead.
func (*PayCallbackResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{16}
}

func (x *PayCallbackResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PayCallbackResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_member_proto protoreflect.FileDescriptor

const file_member_proto_rawDesc = "" +
	"\n" +
	"\fmember.proto\x12\x04user\"+\n" +
	"\x11MemberInfoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x94\x01\n" +
	"\x0eMemberInfoData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x1c\n" +
	"\tlevelName\x18\x03 \x01(\tR\tlevelName\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"d\n" +
	"\x12MemberInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.user.MemberInfoDataR\x04data\"\xc6\x01\n" +
	"\x14UpgradeMemberRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x03 \x01(\x05R\fdurationDays\x12$\n" +
	"\rtransactionId\x18\x04 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x06 \x01(\tR\n" +
	"payChannel\"=\n" +
	"\x15UpgradeMemberResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"M\n" +
	"\x17CheckMemberRightRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\brightKey\x18\x02 \x01(\tR\brightKey\"H\n" +
	"\x14CheckMemberRightData\x12\x1a\n" +
	"\bhasRight\x18\x01 \x01(\bR\bhasRight\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"p\n" +
	"\x18CheckMemberRightResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.user.CheckMemberRightDataR\x04data\"d\n" +
	"\x16MemberOrderListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\xe3\x01\n" +
	"\x0fMemberOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x04 \x01(\x05R\fdurationDays\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x06 \x01(\tR\n" +
	"payChannel\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\"p\n" +
	"\x13MemberOrderListData\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.user.MemberOrderItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"n\n" +
	"\x17MemberOrderListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.user.MemberOrderListDataR\x04data\"\x9e\x01\n" +
	"\x12CreateOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x03 \x01(\x05R\fdurationDays\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x05 \x01(\tR\n" +
	"payChannel\"C\n" +
	"\x0fCreateOrderData\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"f\n" +
	"\x13CreateOrderResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.user.CreateOrderDataR\x04data\"T\n" +
	"\x12PayCallbackRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12$\n" +
	"\rtransactionId\x18\x02 \x01(\tR\rtransactionId\";\n" +
	"\x13PayCallbackResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xbe\x03\n" +
	"\x06Member\x12?\n" +
	"\n" +
	"MemberInfo\x12\x17.user.MemberInfoRequest\x1a\x18.user.MemberInfoResponse\x12H\n" +
	"\rUpgradeMember\x12\x1a.user.UpgradeMemberRequest\x1a\x1b.user.UpgradeMemberResponse\x12Q\n" +
	"\x10CheckMemberRight\x12\x1d.user.CheckMemberRightRequest\x1a\x1e.user.CheckMemberRightResponse\x12N\n" +
	"\x0fMemberOrderList\x12\x1c.user.MemberOrderListRequest\x1a\x1d.user.MemberOrderListResponse\x12B\n" +
	"\vCreateOrder\x12\x18.user.CreateOrderRequest\x1a\x19.user.CreateOrderResponse\x12B\n" +
	"\vPayCallback\x12\x18.user.PayCallbackRequest\x1a\x19.user.PayCallbackResponseB#Z!api-thinktalk/client/member/pb;pbb\x06proto3"

var (
	file_member_proto_rawDescOnce sync.Once
	file_member_proto_rawDescData []byte
)

func file_member_proto_rawDescGZIP() []byte {
	file_member_proto_rawDescOnce.Do(func() {
		file_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)))
	})
	return file_member_proto_rawDescData
}

var file_member_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_member_proto_goTypes = []any{
	(*MemberInfoRequest)(nil),        // 0: user.MemberInfoRequest
	(*MemberInfoData)(nil),           // 1: user.MemberInfoData
	(*MemberInfoResponse)(nil),       // 2: user.MemberInfoResponse
	(*UpgradeMemberRequest)(nil),     // 3: user.UpgradeMemberRequest
	(*UpgradeMemberResponse)(nil),    // 4: user.UpgradeMemberResponse
	(*CheckMemberRightRequest)(nil),  // 5: user.CheckMemberRightRequest
	(*CheckMemberRightData)(nil),     // 6: user.CheckMemberRightData
	(*CheckMemberRightResponse)(nil), // 7: user.CheckMemberRightResponse
	(*MemberOrderListRequest)(nil),   // 8: user.MemberOrderListRequest
	(*MemberOrderItem)(nil),          // 9: user.MemberOrderItem
	(*MemberOrderListData)(nil),      // 10: user.MemberOrderListData
	(*MemberOrderListResponse)(nil),  // 11: user.MemberOrderListResponse
	(*CreateOrderRequest)(nil),       // 12: user.CreateOrderRequest
	(*CreateOrderData)(nil),          // 13: user.CreateOrderData
	(*CreateOrderResponse)(nil),      // 14: user.CreateOrderResponse
	(*PayCallbackRequest)(nil),       // 15: user.PayCallbackRequest
	(*PayCallbackResponse)(nil),      // 16: user.PayCallbackResponse
}
var file_member_proto_depIdxs = []int32{
	1,  // 0: user.MemberInfoResponse.data:type_name -> user.MemberInfoData
	6,  // 1: user.CheckMemberRightResponse.data:type_name -> user.CheckMemberRightData
	9,  // 2: user.MemberOrderListData.items:type_name -> user.MemberOrderItem
	10, // 3: user.MemberOrderListResponse.data:type_name -> user.MemberOrderListData
	13, // 4: user.CreateOrderResponse.data:type_name -> user.CreateOrderData
	0,  // 5: user.Member.MemberInfo:input_type -> user.MemberInfoRequest
	3,  // 6: user.Member.UpgradeMember:input_type -> user.UpgradeMemberRequest
	5,  // 7: user.Member.CheckMemberRight:input_type -> user.CheckMemberRightRequest
	8,  // 8: user.Member.MemberOrderList:input_type -> user.MemberOrderListRequest
	12, // 9: user.Member.CreateOrder:input_type -> user.CreateOrderRequest
	15, // 10: user.Member.PayCallback:input_type -> user.PayCallbackRequest
	2,  // 11: user.Member.MemberInfo:output_type -> user.MemberInfoResponse
	4,  // 12: user.Member.UpgradeMember:output_type -> user.UpgradeMemberResponse
	7,  // 13: user.Member.CheckMemberRight:output_type -> user.CheckMemberRightResponse
	11, // 14: user.Member.MemberOrderList:output_type -> user.MemberOrderListResponse
	14, // 15: user.Member.CreateOrder:output_type -> user.CreateOrderResponse
	16, // 16: user.Member.PayCallback:output_type -> user.PayCallbackResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_member_proto_init() }
func file_member_proto_init() {
	if File_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_proto_goTypes,
		DependencyIndexes: file_member_proto_depIdxs,
		MessageInfos:      file_member_proto_msgTypes,
	}.Build()
	File_member_proto = out.File
	file_member_proto_goTypes = nil
	file_member_proto_depIdxs = nil
}
