// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	agent "api-thinktalk/internal/handler/agent"
	article "api-thinktalk/internal/handler/article"
	chat "api-thinktalk/internal/handler/chat"
	member "api-thinktalk/internal/handler/member"
	qa "api-thinktalk/internal/handler/qa"
	social "api-thinktalk/internal/handler/social"
	tag "api-thinktalk/internal/handler/tag"
	user "api-thinktalk/internal/handler/user"
	video "api-thinktalk/internal/handler/video"
	"api-thinktalk/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: agent.ChatHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: agent.HistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sessions",
				Handler: agent.ListSessionsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/sessions",
				Handler: agent.DeleteSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/stop",
				Handler: agent.StopHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/agent"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/all",
				Handler: article.AllArticlesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: article.ArticleDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: article.ArticleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: article.ArticleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: article.PublishHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: article.SearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload/cover",
				Handler: article.UploadCoverHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload/token",
				Handler: article.UploadTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/article"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/audit",
					Handler: article.AdminAuditHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/pending",
					Handler: article.AdminPendingListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/article/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/conversations",
				Handler: chat.ConversationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/markread",
				Handler: chat.MarkReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/messages",
				Handler: chat.MessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/online",
				Handler: chat.OnlineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: chat.SendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/unread",
				Handler: chat.UnreadCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/chat"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: chat.WebSocketHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/chat"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: member.MemberInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: member.MemberOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/right",
				Handler: member.MemberRightHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/member"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: member.CreateMemberOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/query-status",
				Handler: member.QueryOrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upgrade",
				Handler: member.UpgradeMemberHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/member"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notify",
				Handler: member.AlipayNotifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/member/alipay"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/accept",
				Handler: qa.AcceptAnswerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/answer",
				Handler: qa.AnswerQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/answer/delete",
				Handler: qa.AnswerDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/answers",
				Handler: qa.AnswerListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: qa.QuestionDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: qa.QuestionDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: qa.QuestionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: qa.PublishQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: qa.SearchQuestionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/qa"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/thumbup",
				Handler: social.ThumbupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/thumbup",
				Handler: social.IsThumbupHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/like"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/fans",
				Handler: social.FansListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: social.FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: social.FollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unfollow",
				Handler: social.UnFollowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/follow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: social.ConcernedAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cancel",
				Handler: social.ConcernedCancelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/check",
				Handler: social.ConcernedCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/count",
				Handler: social.ConcernedCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: social.ConcernedListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/concerned"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: social.DeleteNotificationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: social.NotificationListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: social.MarkReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/readall",
				Handler: social.MarkAllReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/unread",
				Handler: social.UnreadCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/message"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/list",
				Handler: social.AdminReplyListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/count",
				Handler: social.ReplyCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: social.ReplyDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: social.ReplyListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/reply"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: social.ReplyCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: social.ReplyDeleteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/reply"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/delete",
					Handler: social.AdminDeleteReplyHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/reply"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/broadcast",
					Handler: social.AdminBroadcastHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/admin/notification"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: tag.TagDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/hot",
				Handler: tag.HotTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: tag.TagListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resource/list",
				Handler: tag.ResourcesByTagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resource/tags",
				Handler: tag.TagsByResourceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/tag"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: tag.TagCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: tag.TagDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resource/add",
				Handler: tag.TagResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resource/remove",
				Handler: tag.UntagResourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: tag.TagUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/tag"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verification",
				Handler: user.VerificationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/profile",
				Handler: user.UserProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/update",
				Handler: user.UpdateProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: user.AdminUserListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/admin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/status",
					Handler: video.VideoStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/complete",
					Handler: video.UploadCompleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/init",
					Handler: video.UploadInitHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/video"),
	)
}
