// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: like.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThumbupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	LikeType      int32                  `protobuf:"varint,4,opt,name=likeType,proto3" json:"likeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbupRequest) Reset() {
	*x = ThumbupRequest{}
	mi := &file_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbupRequest) ProtoMessage() {}

func (x *ThumbupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbupRequest.ProtoReflect.Descriptor instead.
func (*ThumbupRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{0}
}

func (x *ThumbupRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ThumbupRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *ThumbupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ThumbupRequest) GetLikeType() int32 {
	if x != nil {
		return x.LikeType
	}
	return 0
}

type ThumbupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=objId,proto3" json:"objId,omitempty"`
	LikeNum       int64                  `protobuf:"varint,3,opt,name=likeNum,proto3" json:"likeNum,omitempty"`
	DislikeNum    int64                  `protobuf:"varint,4,opt,name=dislikeNum,proto3" json:"dislikeNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbupData) Reset() {
	*x = ThumbupData{}
	mi := &file_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbupData) ProtoMessage() {}

func (x *ThumbupData) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbupData.ProtoReflect.Descriptor instead.
func (*ThumbupData) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{1}
}

func (x *ThumbupData) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ThumbupData) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *ThumbupData) GetLikeNum() int64 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *ThumbupData) GetDislikeNum() int64 {
	if x != nil {
		return x.DislikeNum
	}
	return 0
}

type ThumbupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ThumbupData           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbupResponse) Reset() {
	*x = ThumbupResponse{}
	mi := &file_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbupResponse) ProtoMessage() {}

func (x *ThumbupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbupResponse.ProtoReflect.Descriptor instead.
func (*ThumbupResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{2}
}

func (x *ThumbupResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ThumbupResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ThumbupResponse) GetData() *ThumbupData {
	if x != nil {
		return x.Data
	}
	return nil
}

type IsThumbupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsThumbupRequest) Reset() {
	*x = IsThumbupRequest{}
	mi := &file_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsThumbupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsThumbupRequest) ProtoMessage() {}

func (x *IsThumbupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsThumbupRequest.ProtoReflect.Descriptor instead.
func (*IsThumbupRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{3}
}

func (x *IsThumbupRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *IsThumbupRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *IsThumbupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserThumbup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ThumbupTime   int64                  `protobuf:"varint,2,opt,name=thumbupTime,proto3" json:"thumbupTime,omitempty"`
	LikeType      int32                  `protobuf:"varint,3,opt,name=likeType,proto3" json:"likeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserThumbup) Reset() {
	*x = UserThumbup{}
	mi := &file_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserThumbup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserThumbup) ProtoMessage() {}

func (x *UserThumbup) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserThumbup.ProtoReflect.Descriptor instead.
func (*UserThumbup) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{4}
}

func (x *UserThumbup) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserThumbup) GetThumbupTime() int64 {
	if x != nil {
		return x.ThumbupTime
	}
	return 0
}

func (x *UserThumbup) GetLikeType() int32 {
	if x != nil {
		return x.LikeType
	}
	return 0
}

type IsThumbupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserThumbups  map[int64]*UserThumbup `protobuf:"bytes,1,rep,name=userThumbups,proto3" json:"userThumbups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsThumbupData) Reset() {
	*x = IsThumbupData{}
	mi := &file_like_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsThumbupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsThumbupData) ProtoMessage() {}

func (x *IsThumbupData) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsThumbupData.ProtoReflect.Descriptor instead.
func (*IsThumbupData) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{5}
}

func (x *IsThumbupData) GetUserThumbups() map[int64]*UserThumbup {
	if x != nil {
		return x.UserThumbups
	}
	return nil
}

type IsThumbupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *IsThumbupData         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsThumbupResponse) Reset() {
	*x = IsThumbupResponse{}
	mi := &file_like_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsThumbupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsThumbupResponse) ProtoMessage() {}

func (x *IsThumbupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsThumbupResponse.ProtoReflect.Descriptor instead.
func (*IsThumbupResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{6}
}

func (x *IsThumbupResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IsThumbupResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *IsThumbupResponse) GetData() *IsThumbupData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_like_proto protoreflect.FileDescriptor

const file_like_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"like.proto\x12\x06social\"p\n" +
	"\x0eThumbupRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\blikeType\x18\x04 \x01(\x05R\blikeType\"s\n" +
	"\vThumbupData\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x14\n" +
	"\x05objId\x18\x02 \x01(\x03R\x05objId\x12\x18\n" +
	"\alikeNum\x18\x03 \x01(\x03R\alikeNum\x12\x1e\n" +
	"\n" +
	"dislikeNum\x18\x04 \x01(\x03R\n" +
	"dislikeNum\"`\n" +
	"\x0fThumbupResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.social.ThumbupDataR\x04data\"\\\n" +
	"\x10IsThumbupRequest\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\tR\x05bizId\x12\x1a\n" +
	"\btargetId\x18\x02 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"c\n" +
	"\vUserThumbup\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vthumbupTime\x18\x02 \x01(\x03R\vthumbupTime\x12\x1a\n" +
	"\blikeType\x18\x03 \x01(\x05R\blikeType\"\xb2\x01\n" +
	"\rIsThumbupData\x12K\n" +
	"\fuserThumbups\x18\x01 \x03(\v2'.social.IsThumbupData.UserThumbupsEntryR\fuserThumbups\x1aT\n" +
	"\x11UserThumbupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.social.UserThumbupR\x05value:\x028\x01\"d\n" +
	"\x11IsThumbupResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.social.IsThumbupDataR\x04data2\x84\x01\n" +
	"\x04Like\x12:\n" +
	"\aThumbup\x12\x16.social.ThumbupRequest\x1a\x17.social.ThumbupResponse\x12@\n" +
	"\tIsThumbup\x12\x18.social.IsThumbupRequest\x1a\x19.social.IsThumbupResponseB+Z)api-thinktalk/client/like/service;serviceb\x06proto3"

var (
	file_like_proto_rawDescOnce sync.Once
	file_like_proto_rawDescData []byte
)

func file_like_proto_rawDescGZIP() []byte {
	file_like_proto_rawDescOnce.Do(func() {
		file_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)))
	})
	return file_like_proto_rawDescData
}

var file_like_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_like_proto_goTypes = []any{
	(*ThumbupRequest)(nil),    // 0: social.ThumbupRequest
	(*ThumbupData)(nil),       // 1: social.ThumbupData
	(*ThumbupResponse)(nil),   // 2: social.ThumbupResponse
	(*IsThumbupRequest)(nil),  // 3: social.IsThumbupRequest
	(*UserThumbup)(nil),       // 4: social.UserThumbup
	(*IsThumbupData)(nil),     // 5: social.IsThumbupData
	(*IsThumbupResponse)(nil), // 6: social.IsThumbupResponse
	nil,                       // 7: social.IsThumbupData.UserThumbupsEntry
}
var file_like_proto_depIdxs = []int32{
	1, // 0: social.ThumbupResponse.data:type_name -> social.ThumbupData
	7, // 1: social.IsThumbupData.userThumbups:type_name -> social.IsThumbupData.UserThumbupsEntry
	5, // 2: social.IsThumbupResponse.data:type_name -> social.IsThumbupData
	4, // 3: social.IsThumbupData.UserThumbupsEntry.value:type_name -> social.UserThumbup
	0, // 4: social.Like.Thumbup:input_type -> social.ThumbupRequest
	3, // 5: social.Like.IsThumbup:input_type -> social.IsThumbupRequest
	2, // 6: social.Like.Thumbup:output_type -> social.ThumbupResponse
	6, // 7: social.Like.IsThumbup:output_type -> social.IsThumbupResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_like_proto_init() }
func file_like_proto_init() {
	if File_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_like_proto_goTypes,
		DependencyIndexes: file_like_proto_depIdxs,
		MessageInfos:      file_like_proto_msgTypes,
	}.Build()
	File_like_proto = out.File
	file_like_proto_goTypes = nil
	file_like_proto_depIdxs = nil
}
