// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: article.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	TagIds        []int64                `protobuf:"varint,6,rep,packed,name=tagIds,proto3" json:"tagIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *PublishRequest) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type PublishData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishData) Reset() {
	*x = PublishData{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishData) ProtoMessage() {}

func (x *PublishData) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishData.ProtoReflect.Descriptor instead.
func (*PublishData) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *PublishData) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *PublishData           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PublishResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PublishResponse) GetData() *PublishData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SortType      int32                  `protobuf:"varint,4,opt,name=sortType,proto3" json:"sortType,omitempty"`
	ArticleId     int64                  `protobuf:"varint,5,opt,name=articleId,proto3" json:"articleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlesRequest) Reset() {
	*x = ArticlesRequest{}
	mi := &file_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlesRequest) ProtoMessage() {}

func (x *ArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlesRequest.ProtoReflect.Descriptor instead.
func (*ArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{3}
}

func (x *ArticlesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ArticlesRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ArticlesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ArticlesRequest) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

func (x *ArticlesRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ArticleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	CommentCount  int64                  `protobuf:"varint,6,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	PublishTime   int64                  `protobuf:"varint,8,opt,name=publishTime,proto3" json:"publishTime,omitempty"`
	AuthorId      int64                  `protobuf:"varint,9,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Status        int64                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleItem) Reset() {
	*x = ArticleItem{}
	mi := &file_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleItem) ProtoMessage() {}

func (x *ArticleItem) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleItem.ProtoReflect.Descriptor instead.
func (*ArticleItem) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArticleItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ArticleItem) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ArticleItem) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ArticleItem) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *ArticleItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ArticlesData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*ArticleItem         `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	IsEnd         bool                   `protobuf:"varint,2,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	ArticleId     int64                  `protobuf:"varint,4,opt,name=articleId,proto3" json:"articleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlesData) Reset() {
	*x = ArticlesData{}
	mi := &file_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlesData) ProtoMessage() {}

func (x *ArticlesData) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlesData.ProtoReflect.Descriptor instead.
func (*ArticlesData) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{5}
}

func (x *ArticlesData) GetArticles() []*ArticleItem {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ArticlesData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *ArticlesData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ArticlesData) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ArticlesData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlesResponse) Reset() {
	*x = ArticlesResponse{}
	mi := &file_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlesResponse) ProtoMessage() {}

func (x *ArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlesResponse.ProtoReflect.Descriptor instead.
func (*ArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{6}
}

func (x *ArticlesResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ArticlesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ArticlesResponse) GetData() *ArticlesData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArticleDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ArticleId     int64                  `protobuf:"varint,2,opt,name=articleId,proto3" json:"articleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDeleteRequest) Reset() {
	*x = ArticleDeleteRequest{}
	mi := &file_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDeleteRequest) ProtoMessage() {}

func (x *ArticleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDeleteRequest.ProtoReflect.Descriptor instead.
func (*ArticleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{7}
}

func (x *ArticleDeleteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ArticleDeleteRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ArticleDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDeleteResponse) Reset() {
	*x = ArticleDeleteResponse{}
	mi := &file_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDeleteResponse) ProtoMessage() {}

func (x *ArticleDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDeleteResponse.ProtoReflect.Descriptor instead.
func (*ArticleDeleteResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{8}
}

func (x *ArticleDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ArticleDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ArticleDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDetailRequest) Reset() {
	*x = ArticleDetailRequest{}
	mi := &file_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDetailRequest) ProtoMessage() {}

func (x *ArticleDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDetailRequest.ProtoReflect.Descriptor instead.
func (*ArticleDetailRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{9}
}

func (x *ArticleDetailRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ArticleDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ArticleItem           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDetailResponse) Reset() {
	*x = ArticleDetailResponse{}
	mi := &file_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDetailResponse) ProtoMessage() {}

func (x *ArticleDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDetailResponse.ProtoReflect.Descriptor instead.
func (*ArticleDetailResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{10}
}

func (x *ArticleDetailResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ArticleDetailResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ArticleDetailResponse) GetData() *ArticleItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SortType      int32                  `protobuf:"varint,4,opt,name=sortType,proto3" json:"sortType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

type SearchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	AuthorId      int64                  `protobuf:"varint,5,opt,name=authorId,proto3" json:"authorId,omitempty"`
	AuthorName    string                 `protobuf:"bytes,6,opt,name=authorName,proto3" json:"authorName,omitempty"`
	LikeNum       int64                  `protobuf:"varint,7,opt,name=likeNum,proto3" json:"likeNum,omitempty"`
	CommentNum    int64                  `protobuf:"varint,8,opt,name=commentNum,proto3" json:"commentNum,omitempty"`
	PublishTime   string                 `protobuf:"bytes,9,opt,name=publishTime,proto3" json:"publishTime,omitempty"`
	AuthorAvatar  string                 `protobuf:"bytes,10,opt,name=authorAvatar,proto3" json:"authorAvatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItem) Reset() {
	*x = SearchItem{}
	mi := &file_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItem) ProtoMessage() {}

func (x *SearchItem) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItem.ProtoReflect.Descriptor instead.
func (*SearchItem) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{12}
}

func (x *SearchItem) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *SearchItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *SearchItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SearchItem) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *SearchItem) GetLikeNum() int64 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *SearchItem) GetCommentNum() int64 {
	if x != nil {
		return x.CommentNum
	}
	return 0
}

func (x *SearchItem) GetPublishTime() string {
	if x != nil {
		return x.PublishTime
	}
	return ""
}

func (x *SearchItem) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

type SearchData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SearchItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchData) Reset() {
	*x = SearchData{}
	mi := &file_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchData) ProtoMessage() {}

func (x *SearchData) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchData.ProtoReflect.Descriptor instead.
func (*SearchData) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{13}
}

func (x *SearchData) GetItems() []*SearchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SearchData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SearchData            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchResponse) GetData() *SearchData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdminPendingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPendingListRequest) Reset() {
	*x = AdminPendingListRequest{}
	mi := &file_article_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPendingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPendingListRequest) ProtoMessage() {}

func (x *AdminPendingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPendingListRequest.ProtoReflect.Descriptor instead.
func (*AdminPendingListRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{15}
}

func (x *AdminPendingListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *AdminPendingListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminPendingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SearchData            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPendingListResponse) Reset() {
	*x = AdminPendingListResponse{}
	mi := &file_article_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPendingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPendingListResponse) ProtoMessage() {}

func (x *AdminPendingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPendingListResponse.ProtoReflect.Descriptor instead.
func (*AdminPendingListResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{16}
}

func (x *AdminPendingListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminPendingListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AdminPendingListResponse) GetData() *SearchData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdminAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuditRequest) Reset() {
	*x = AdminAuditRequest{}
	mi := &file_article_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuditRequest) ProtoMessage() {}

func (x *AdminAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuditRequest.ProtoReflect.Descriptor instead.
func (*AdminAuditRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{17}
}

func (x *AdminAuditRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *AdminAuditRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuditResponse) Reset() {
	*x = AdminAuditResponse{}
	mi := &file_article_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuditResponse) ProtoMessage() {}

func (x *AdminAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuditResponse.ProtoReflect.Descriptor instead.
func (*AdminAuditResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{18}
}

func (x *AdminAuditResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminAuditResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_article_proto protoreflect.FileDescriptor

const file_article_proto_rawDesc = "" +
	"\n" +
	"\rarticle.proto\x12\acontent\"\xa8\x01\n" +
	"\x0ePublishRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x16\n" +
	"\x06tagIds\x18\x06 \x03(\x03R\x06tagIds\"+\n" +
	"\vPublishData\x12\x1c\n" +
	"\tarticleId\x18\x01 \x01(\x03R\tarticleId\"a\n" +
	"\x0fPublishResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.content.PublishDataR\x04data\"\x97\x01\n" +
	"\x0fArticlesRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bsortType\x18\x04 \x01(\x05R\bsortType\x12\x1c\n" +
	"\tarticleId\x18\x05 \x01(\x03R\tarticleId\"\x9d\x02\n" +
	"\vArticleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\"\n" +
	"\fcommentCount\x18\x06 \x01(\x03R\fcommentCount\x12\x1c\n" +
	"\tlikeCount\x18\a \x01(\x03R\tlikeCount\x12 \n" +
	"\vpublishTime\x18\b \x01(\x03R\vpublishTime\x12\x1a\n" +
	"\bauthorId\x18\t \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x03R\x06status\"\x8c\x01\n" +
	"\fArticlesData\x120\n" +
	"\barticles\x18\x01 \x03(\v2\x14.content.ArticleItemR\barticles\x12\x14\n" +
	"\x05isEnd\x18\x02 \x01(\bR\x05isEnd\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1c\n" +
	"\tarticleId\x18\x04 \x01(\x03R\tarticleId\"c\n" +
	"\x10ArticlesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.content.ArticlesDataR\x04data\"L\n" +
	"\x14ArticleDeleteRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tarticleId\x18\x02 \x01(\x03R\tarticleId\"=\n" +
	"\x15ArticleDeleteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"4\n" +
	"\x14ArticleDetailRequest\x12\x1c\n" +
	"\tarticleId\x18\x01 \x01(\x03R\tarticleId\"g\n" +
	"\x15ArticleDetailResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.content.ArticleItemR\x04data\"y\n" +
	"\rSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bsortType\x18\x04 \x01(\x05R\bsortType\"\xb4\x02\n" +
	"\n" +
	"SearchItem\x12\x1c\n" +
	"\tarticleId\x18\x01 \x01(\x03R\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x1a\n" +
	"\bauthorId\x18\x05 \x01(\x03R\bauthorId\x12\x1e\n" +
	"\n" +
	"authorName\x18\x06 \x01(\tR\n" +
	"authorName\x12\x18\n" +
	"\alikeNum\x18\a \x01(\x03R\alikeNum\x12\x1e\n" +
	"\n" +
	"commentNum\x18\b \x01(\x03R\n" +
	"commentNum\x12 \n" +
	"\vpublishTime\x18\t \x01(\tR\vpublishTime\x12\"\n" +
	"\fauthorAvatar\x18\n" +
	" \x01(\tR\fauthorAvatar\"e\n" +
	"\n" +
	"SearchData\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.content.SearchItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"_\n" +
	"\x0eSearchResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.content.SearchDataR\x04data\"M\n" +
	"\x17AdminPendingListRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"i\n" +
	"\x18AdminPendingListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.content.SearchDataR\x04data\"I\n" +
	"\x11AdminAuditRequest\x12\x1c\n" +
	"\tarticleId\x18\x01 \x01(\x03R\tarticleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\":\n" +
	"\x12AdminAuditResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x8b\x04\n" +
	"\aArticle\x12<\n" +
	"\aPublish\x12\x17.content.PublishRequest\x1a\x18.content.PublishResponse\x12?\n" +
	"\bArticles\x12\x18.content.ArticlesRequest\x1a\x19.content.ArticlesResponse\x12N\n" +
	"\rArticleDelete\x12\x1d.content.ArticleDeleteRequest\x1a\x1e.content.ArticleDeleteResponse\x12N\n" +
	"\rArticleDetail\x12\x1d.content.ArticleDetailRequest\x1a\x1e.content.ArticleDetailResponse\x12A\n" +
	"\x0eSearchArticles\x12\x16.content.SearchRequest\x1a\x17.content.SearchResponse\x12W\n" +
	"\x10AdminPendingList\x12 .content.AdminPendingListRequest\x1a!.content.AdminPendingListResponse\x12E\n" +
	"\n" +
	"AdminAudit\x12\x1a.content.AdminAuditRequest\x1a\x1b.content.AdminAuditResponseB$Z\"api-thinktalk/client/article/pb;pbb\x06proto3"

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData []byte
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)))
	})
	return file_article_proto_rawDescData
}

var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_article_proto_goTypes = []any{
	(*PublishRequest)(nil),           // 0: content.PublishRequest
	(*PublishData)(nil),              // 1: content.PublishData
	(*PublishResponse)(nil),          // 2: content.PublishResponse
	(*ArticlesRequest)(nil),          // 3: content.ArticlesRequest
	(*ArticleItem)(nil),              // 4: content.ArticleItem
	(*ArticlesData)(nil),             // 5: content.ArticlesData
	(*ArticlesResponse)(nil),         // 6: content.ArticlesResponse
	(*ArticleDeleteRequest)(nil),     // 7: content.ArticleDeleteRequest
	(*ArticleDeleteResponse)(nil),    // 8: content.ArticleDeleteResponse
	(*ArticleDetailRequest)(nil),     // 9: content.ArticleDetailRequest
	(*ArticleDetailResponse)(nil),    // 10: content.ArticleDetailResponse
	(*SearchRequest)(nil),            // 11: content.SearchRequest
	(*SearchItem)(nil),               // 12: content.SearchItem
	(*SearchData)(nil),               // 13: content.SearchData
	(*SearchResponse)(nil),           // 14: content.SearchResponse
	(*AdminPendingListRequest)(nil),  // 15: content.AdminPendingListRequest
	(*AdminPendingListResponse)(nil), // 16: content.AdminPendingListResponse
	(*AdminAuditRequest)(nil),        // 17: content.AdminAuditRequest
	(*AdminAuditResponse)(nil),       // 18: content.AdminAuditResponse
}
var file_article_proto_depIdxs = []int32{
	1,  // 0: content.PublishResponse.data:type_name -> content.PublishData
	4,  // 1: content.ArticlesData.articles:type_name -> content.ArticleItem
	5,  // 2: content.ArticlesResponse.data:type_name -> content.ArticlesData
	4,  // 3: content.ArticleDetailResponse.data:type_name -> content.ArticleItem
	12, // 4: content.SearchData.items:type_name -> content.SearchItem
	13, // 5: content.SearchResponse.data:type_name -> content.SearchData
	13, // 6: content.AdminPendingListResponse.data:type_name -> content.SearchData
	0,  // 7: content.Article.Publish:input_type -> content.PublishRequest
	3,  // 8: content.Article.Articles:input_type -> content.ArticlesRequest
	7,  // 9: content.Article.ArticleDelete:input_type -> content.ArticleDeleteRequest
	9,  // 10: content.Article.ArticleDetail:input_type -> content.ArticleDetailRequest
	11, // 11: content.Article.SearchArticles:input_type -> content.SearchRequest
	15, // 12: content.Article.AdminPendingList:input_type -> content.AdminPendingListRequest
	17, // 13: content.Article.AdminAudit:input_type -> content.AdminAuditRequest
	2,  // 14: content.Article.Publish:output_type -> content.PublishResponse
	6,  // 15: content.Article.Articles:output_type -> content.ArticlesResponse
	8,  // 16: content.Article.ArticleDelete:output_type -> content.ArticleDeleteResponse
	10, // 17: content.Article.ArticleDetail:output_type -> content.ArticleDetailResponse
	14, // 18: content.Article.SearchArticles:output_type -> content.SearchResponse
	16, // 19: content.Article.AdminPendingList:output_type -> content.AdminPendingListResponse
	18, // 20: content.Article.AdminAudit:output_type -> content.AdminAuditResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
