// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MsgType       int32                  `protobuf:"varint,4,opt,name=msgType,proto3" json:"msgType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

type SendMessageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageData) Reset() {
	*x = SendMessageData{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageData) ProtoMessage() {}

func (x *SendMessageData) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageData.ProtoReflect.Descriptor instead.
func (*SendMessageData) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageData) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SendMessageData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendMessageResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendMessageResponse) GetData() *SendMessageData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationsRequest) Reset() {
	*x = ConversationsRequest{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationsRequest) ProtoMessage() {}

func (x *ConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationsRequest.ProtoReflect.Descriptor instead.
func (*ConversationsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ConversationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConversationsRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ConversationsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ConversationItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetUserId    int64                  `protobuf:"varint,2,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	LastMessage     string                 `protobuf:"bytes,3,opt,name=lastMessage,proto3" json:"lastMessage,omitempty"`
	LastMessageTime int64                  `protobuf:"varint,4,opt,name=lastMessageTime,proto3" json:"lastMessageTime,omitempty"`
	UnreadCount     int64                  `protobuf:"varint,5,opt,name=unreadCount,proto3" json:"unreadCount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConversationItem) Reset() {
	*x = ConversationItem{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationItem) ProtoMessage() {}

func (x *ConversationItem) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationItem.ProtoReflect.Descriptor instead.
func (*ConversationItem) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConversationItem) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *ConversationItem) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *ConversationItem) GetLastMessageTime() int64 {
	if x != nil {
		return x.LastMessageTime
	}
	return 0
}

func (x *ConversationItem) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ConversationsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConversationItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationsData) Reset() {
	*x = ConversationsData{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationsData) ProtoMessage() {}

func (x *ConversationsData) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationsData.ProtoReflect.Descriptor instead.
func (*ConversationsData) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationsData) GetItems() []*ConversationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ConversationsData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ConversationsData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type ConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ConversationsData     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationsResponse) Reset() {
	*x = ConversationsResponse{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationsResponse) ProtoMessage() {}

func (x *ConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationsResponse.ProtoReflect.Descriptor instead.
func (*ConversationsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConversationsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConversationsResponse) GetData() *ConversationsData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	Cursor         int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize       int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessagesRequest) Reset() {
	*x = MessagesRequest{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesRequest) ProtoMessage() {}

func (x *MessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesRequest.ProtoReflect.Descriptor instead.
func (*MessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *MessagesRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MessagesRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MessagesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MessageItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	SenderId       int64                  `protobuf:"varint,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId     int64                  `protobuf:"varint,4,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MsgType        int32                  `protobuf:"varint,6,opt,name=msgType,proto3" json:"msgType,omitempty"`
	IsRead         bool                   `protobuf:"varint,7,opt,name=isRead,proto3" json:"isRead,omitempty"`
	CreateTime     int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *MessageItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageItem) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MessageItem) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageItem) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MessageItem) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MessageItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type MessagesData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MessageItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesData) Reset() {
	*x = MessagesData{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesData) ProtoMessage() {}

func (x *MessagesData) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesData.ProtoReflect.Descriptor instead.
func (*MessagesData) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *MessagesData) GetItems() []*MessageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MessagesData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MessagesData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type MessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *MessagesData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesResponse) Reset() {
	*x = MessagesResponse{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesResponse) ProtoMessage() {}

func (x *MessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesResponse.ProtoReflect.Descriptor instead.
func (*MessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *MessagesResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MessagesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MessagesResponse) GetData() *MessagesData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatMarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatMarkReadRequest) Reset() {
	*x = ChatMarkReadRequest{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMarkReadRequest) ProtoMessage() {}

func (x *ChatMarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMarkReadRequest.ProtoReflect.Descriptor instead.
func (*ChatMarkReadRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMarkReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatMarkReadRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type ChatMarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMarkReadResponse) Reset() {
	*x = ChatMarkReadResponse{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMarkReadResponse) ProtoMessage() {}

func (x *ChatMarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMarkReadResponse.ProtoReflect.Descriptor instead.
func (*ChatMarkReadResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *ChatMarkReadResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatMarkReadResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ChatUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUnreadCountRequest) Reset() {
	*x = ChatUnreadCountRequest{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUnreadCountRequest) ProtoMessage() {}

func (x *ChatUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*ChatUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *ChatUnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ChatUnreadCountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUnreadCountData) Reset() {
	*x = ChatUnreadCountData{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUnreadCountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUnreadCountData) ProtoMessage() {}

func (x *ChatUnreadCountData) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUnreadCountData.ProtoReflect.Descriptor instead.
func (*ChatUnreadCountData) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ChatUnreadCountData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ChatUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ChatUnreadCountData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUnreadCountResponse) Reset() {
	*x = ChatUnreadCountResponse{}
	mi := &file_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUnreadCountResponse) ProtoMessage() {}

func (x *ChatUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*ChatUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *ChatUnreadCountResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatUnreadCountResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatUnreadCountResponse) GetData() *ChatUnreadCountData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x06social\"\x84\x01\n" +
	"\x12SendMessageRequest\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\x03R\bsenderId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x02 \x01(\x03R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\amsgType\x18\x04 \x01(\x05R\amsgType\"/\n" +
	"\x0fSendMessageData\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\x03R\tmessageId\"h\n" +
	"\x13SendMessageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.social.SendMessageDataR\x04data\"b\n" +
	"\x14ConversationsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\xb4\x01\n" +
	"\x10ConversationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\ftargetUserId\x18\x02 \x01(\x03R\ftargetUserId\x12 \n" +
	"\vlastMessage\x18\x03 \x01(\tR\vlastMessage\x12(\n" +
	"\x0flastMessageTime\x18\x04 \x01(\x03R\x0flastMessageTime\x12 \n" +
	"\vunreadCount\x18\x05 \x01(\x03R\vunreadCount\"q\n" +
	"\x11ConversationsData\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.social.ConversationItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"l\n" +
	"\x15ConversationsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.social.ConversationsDataR\x04data\"m\n" +
	"\x0fMessagesRequest\x12&\n" +
	"\x0econversationId\x18\x01 \x01(\x03R\x0econversationId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\xed\x01\n" +
	"\vMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0econversationId\x18\x02 \x01(\x03R\x0econversationId\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\x03R\bsenderId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x04 \x01(\x03R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x18\n" +
	"\amsgType\x18\x06 \x01(\x05R\amsgType\x12\x16\n" +
	"\x06isRead\x18\a \x01(\bR\x06isRead\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\"g\n" +
	"\fMessagesData\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.social.MessageItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"b\n" +
	"\x10MessagesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.social.MessagesDataR\x04data\"U\n" +
	"\x13ChatMarkReadRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0econversationId\x18\x02 \x01(\x03R\x0econversationId\"<\n" +
	"\x14ChatMarkReadResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"0\n" +
	"\x16ChatUnreadCountRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"+\n" +
	"\x13ChatUnreadCountData\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"p\n" +
	"\x17ChatUnreadCountResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.social.ChatUnreadCountDataR\x04data2\xf2\x02\n" +
	"\x04Chat\x12F\n" +
	"\vSendMessage\x12\x1a.social.SendMessageRequest\x1a\x1b.social.SendMessageResponse\x12L\n" +
	"\rConversations\x12\x1c.social.ConversationsRequest\x1a\x1d.social.ConversationsResponse\x12=\n" +
	"\bMessages\x12\x17.social.MessagesRequest\x1a\x18.social.MessagesResponse\x12E\n" +
	"\bMarkRead\x12\x1b.social.ChatMarkReadRequest\x1a\x1c.social.ChatMarkReadResponse\x12N\n" +
	"\vUnreadCount\x12\x1e.social.ChatUnreadCountRequest\x1a\x1f.social.ChatUnreadCountResponseB!Z\x1fapi-thinktalk/client/chat/pb;pbb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_chat_proto_goTypes = []any{
	(*SendMessageRequest)(nil),      // 0: social.SendMessageRequest
	(*SendMessageData)(nil),         // 1: social.SendMessageData
	(*SendMessageResponse)(nil),     // 2: social.SendMessageResponse
	(*ConversationsRequest)(nil),    // 3: social.ConversationsRequest
	(*ConversationItem)(nil),        // 4: social.ConversationItem
	(*ConversationsData)(nil),       // 5: social.ConversationsData
	(*ConversationsResponse)(nil),   // 6: social.ConversationsResponse
	(*MessagesRequest)(nil),         // 7: social.MessagesRequest
	(*MessageItem)(nil),             // 8: social.MessageItem
	(*MessagesData)(nil),            // 9: social.MessagesData
	(*MessagesResponse)(nil),        // 10: social.MessagesResponse
	(*ChatMarkReadRequest)(nil),     // 11: social.ChatMarkReadRequest
	(*ChatMarkReadResponse)(nil),    // 12: social.ChatMarkReadResponse
	(*ChatUnreadCountRequest)(nil),  // 13: social.ChatUnreadCountRequest
	(*ChatUnreadCountData)(nil),     // 14: social.ChatUnreadCountData
	(*ChatUnreadCountResponse)(nil), // 15: social.ChatUnreadCountResponse
}
var file_chat_proto_depIdxs = []int32{
	1,  // 0: social.SendMessageResponse.data:type_name -> social.SendMessageData
	4,  // 1: social.ConversationsData.items:type_name -> social.ConversationItem
	5,  // 2: social.ConversationsResponse.data:type_name -> social.ConversationsData
	8,  // 3: social.MessagesData.items:type_name -> social.MessageItem
	9,  // 4: social.MessagesResponse.data:type_name -> social.MessagesData
	14, // 5: social.ChatUnreadCountResponse.data:type_name -> social.ChatUnreadCountData
	0,  // 6: social.Chat.SendMessage:input_type -> social.SendMessageRequest
	3,  // 7: social.Chat.Conversations:input_type -> social.ConversationsRequest
	7,  // 8: social.Chat.Messages:input_type -> social.MessagesRequest
	11, // 9: social.Chat.MarkRead:input_type -> social.ChatMarkReadRequest
	13, // 10: social.Chat.UnreadCount:input_type -> social.ChatUnreadCountRequest
	2,  // 11: social.Chat.SendMessage:output_type -> social.SendMessageResponse
	6,  // 12: social.Chat.Conversations:output_type -> social.ConversationsResponse
	10, // 13: social.Chat.Messages:output_type -> social.MessagesResponse
	12, // 14: social.Chat.MarkRead:output_type -> social.ChatMarkReadResponse
	15, // 15: social.Chat.UnreadCount:output_type -> social.ChatUnreadCountResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
