// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AdminAuditRequest struct {
	ArticleId int64 `json:"article_id"`
	Status    int32 `json:"status"` // 2: approve (visible), 1: reject (not pass)
}

type AdminAuditResponse struct {
}

type AdminPendingListRequest struct {
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type AdminPendingListResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type AllArticlesRequest struct {
	Cursor   int64 `form:"cursor,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type AllArticlesResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type ArticleDeleteRequest struct {
	ArticleId int64 `json:"article_id"`
}

type ArticleDeleteResponse struct {
}

type ArticleDetailRequest struct {
	ArticleId int64 `form:"article_id,optional"`
}

type ArticleDetailResponse struct {
	ArticleId    int64  `json:"article_id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Description  string `json:"description"`
	Cover        string `json:"cover"`
	AuthorId     int64  `json:"author_id"`
	AuthorName   string `json:"author_name"`
	AuthorAvatar string `json:"author_avatar"`
	PublishTime  string `json:"publish_time"`
	LikeNum      int64  `json:"like_num"`
}

type ArticleInfo struct {
	ArticleId   int64  `json:"article_id"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Description string `json:"description"`
	Cover       string `json:"cover"`
	Status      int64  `json:"status"`
}

type ArticleListRequest struct {
	AuthorId  int64 `form:"author_id,optional"`
	Cursor    int64 `form:"cursor,optional"`
	PageSize  int64 `form:"page_size,optional"`
	SortType  int32 `form:"sort_type,optional"`
	ArticleId int64 `form:"article_id,optional"`
}

type ArticleListResponse struct {
	Articles []ArticleInfo `json:"articles"`
}

type PublishRequest struct {
	Title       string  `json:"title"`
	Content     string  `json:"content"`
	Description string  `json:"description"`
	Cover       string  `json:"cover"`
	TagIds      []int64 `json:"tag_ids,optional"`
}

type PublishResponse struct {
	ArticleId int64 `json:"article_id"`
}

type SearchInfo struct {
	ArticleId    int64  `json:"article_id"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	Cover        string `json:"cover"`
	AuthorId     int64  `json:"author_id"`
	AuthorName   string `json:"author_name"`
	LikeNum      int64  `json:"like_num"`
	CommentNum   int64  `json:"comment_num"`
	PublishTime  string `json:"publish_time"`
	AuthorAvatar string `json:"author_avatar"`
}

type SearchRequest struct {
	Keyword  string `form:"keyword"`
	Cursor   int64  `form:"cursor"`
	PageSize int64  `form:"page_size"`
}

type SearchResponse struct {
	Articles []SearchInfo `json:"articles"`
	Cursor   int64        `json:"cursor"`
	IsEnd    bool         `json:"is_end"`
}

type UploadCoverResponse struct {
	CoverUrl string `json:"cover_url"`
}
