// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: follow.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FollowedUserId int64                  `protobuf:"varint,2,opt,name=followedUserId,proto3" json:"followedUserId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetFollowedUserId() int64 {
	if x != nil {
		return x.FollowedUserId
	}
	return 0
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UnFollowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FollowedUserId int64                  `protobuf:"varint,2,opt,name=followedUserId,proto3" json:"followedUserId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnFollowRequest) Reset() {
	*x = UnFollowRequest{}
	mi := &file_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnFollowRequest) ProtoMessage() {}

func (x *UnFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnFollowRequest.ProtoReflect.Descriptor instead.
func (*UnFollowRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{2}
}

func (x *UnFollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnFollowRequest) GetFollowedUserId() int64 {
	if x != nil {
		return x.FollowedUserId
	}
	return 0
}

type UnFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnFollowResponse) Reset() {
	*x = UnFollowResponse{}
	mi := &file_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnFollowResponse) ProtoMessage() {}

func (x *UnFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnFollowResponse.ProtoReflect.Descriptor instead.
func (*UnFollowResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{3}
}

func (x *UnFollowResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnFollowResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListRequest) Reset() {
	*x = FollowListRequest{}
	mi := &file_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListRequest) ProtoMessage() {}

func (x *FollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListRequest.ProtoReflect.Descriptor instead.
func (*FollowListRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{4}
}

func (x *FollowListRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FollowListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FollowItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FollowedUserId int64                  `protobuf:"varint,2,opt,name=followedUserId,proto3" json:"followedUserId,omitempty"`
	FansCount      int64                  `protobuf:"varint,3,opt,name=fansCount,proto3" json:"fansCount,omitempty"`
	CreateTime     int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowItem) Reset() {
	*x = FollowItem{}
	mi := &file_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowItem) ProtoMessage() {}

func (x *FollowItem) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowItem.ProtoReflect.Descriptor instead.
func (*FollowItem) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{5}
}

func (x *FollowItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowItem) GetFollowedUserId() int64 {
	if x != nil {
		return x.FollowedUserId
	}
	return 0
}

func (x *FollowItem) GetFansCount() int64 {
	if x != nil {
		return x.FansCount
	}
	return 0
}

func (x *FollowItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type FollowListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FollowItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListData) Reset() {
	*x = FollowListData{}
	mi := &file_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListData) ProtoMessage() {}

func (x *FollowListData) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListData.ProtoReflect.Descriptor instead.
func (*FollowListData) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{6}
}

func (x *FollowListData) GetItems() []*FollowItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FollowListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FollowListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *FollowListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FollowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *FollowListData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListResponse) Reset() {
	*x = FollowListResponse{}
	mi := &file_follow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListResponse) ProtoMessage() {}

func (x *FollowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListResponse.ProtoReflect.Descriptor instead.
func (*FollowListResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{7}
}

func (x *FollowListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FollowListResponse) GetData() *FollowListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FansListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansListRequest) Reset() {
	*x = FansListRequest{}
	mi := &file_follow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListRequest) ProtoMessage() {}

func (x *FansListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListRequest.ProtoReflect.Descriptor instead.
func (*FansListRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{8}
}

func (x *FansListRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FansListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FansListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FansListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FansItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FansUserId    int64                  `protobuf:"varint,3,opt,name=fansUserId,proto3" json:"fansUserId,omitempty"`
	FollowCount   int64                  `protobuf:"varint,4,opt,name=followCount,proto3" json:"followCount,omitempty"`
	FansCount     int64                  `protobuf:"varint,5,opt,name=fansCount,proto3" json:"fansCount,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansItem) Reset() {
	*x = FansItem{}
	mi := &file_follow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansItem) ProtoMessage() {}

func (x *FansItem) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansItem.ProtoReflect.Descriptor instead.
func (*FansItem) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{9}
}

func (x *FansItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FansItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FansItem) GetFansUserId() int64 {
	if x != nil {
		return x.FansUserId
	}
	return 0
}

func (x *FansItem) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *FansItem) GetFansCount() int64 {
	if x != nil {
		return x.FansCount
	}
	return 0
}

func (x *FansItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type FansListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FansItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansListData) Reset() {
	*x = FansListData{}
	mi := &file_follow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListData) ProtoMessage() {}

func (x *FansListData) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListData.ProtoReflect.Descriptor instead.
func (*FansListData) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{10}
}

func (x *FansListData) GetItems() []*FansItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FansListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FansListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *FansListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FansListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *FansListData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansListResponse) Reset() {
	*x = FansListResponse{}
	mi := &file_follow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListResponse) ProtoMessage() {}

func (x *FansListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListResponse.ProtoReflect.Descriptor instead.
func (*FansListResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{11}
}

func (x *FansListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FansListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FansListResponse) GetData() *FansListData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_follow_proto protoreflect.FileDescriptor

const file_follow_proto_rawDesc = "" +
	"\n" +
	"\ffollow.proto\x12\x04user\"O\n" +
	"\rFollowRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0efollowedUserId\x18\x02 \x01(\x03R\x0efollowedUserId\"6\n" +
	"\x0eFollowResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"Q\n" +
	"\x0fUnFollowRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0efollowedUserId\x18\x02 \x01(\x03R\x0efollowedUserId\"8\n" +
	"\x10UnFollowResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"o\n" +
	"\x11FollowListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\x82\x01\n" +
	"\n" +
	"FollowItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0efollowedUserId\x18\x02 \x01(\x03R\x0efollowedUserId\x12\x1c\n" +
	"\tfansCount\x18\x03 \x01(\x03R\tfansCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\"v\n" +
	"\x0eFollowListData\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.user.FollowItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"d\n" +
	"\x12FollowListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.user.FollowListDataR\x04data\"m\n" +
	"\x0fFansListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\xb2\x01\n" +
	"\bFansItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"fansUserId\x18\x03 \x01(\x03R\n" +
	"fansUserId\x12 \n" +
	"\vfollowCount\x18\x04 \x01(\x03R\vfollowCount\x12\x1c\n" +
	"\tfansCount\x18\x05 \x01(\x03R\tfansCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\x03R\n" +
	"createTime\"r\n" +
	"\fFansListData\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.user.FansItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"`\n" +
	"\x10FansListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.user.FansListDataR\x04data2\xf4\x01\n" +
	"\x06Follow\x123\n" +
	"\x06Follow\x12\x13.user.FollowRequest\x1a\x14.user.FollowResponse\x129\n" +
	"\bUnFollow\x12\x15.user.UnFollowRequest\x1a\x16.user.UnFollowResponse\x12?\n" +
	"\n" +
	"FollowList\x12\x17.user.FollowListRequest\x1a\x18.user.FollowListResponse\x129\n" +
	"\bFansList\x12\x15.user.FansListRequest\x1a\x16.user.FansListResponseB#Z!api-thinktalk/client/follow/pb;pbb\x06proto3"

var (
	file_follow_proto_rawDescOnce sync.Once
	file_follow_proto_rawDescData []byte
)

func file_follow_proto_rawDescGZIP() []byte {
	file_follow_proto_rawDescOnce.Do(func() {
		file_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)))
	})
	return file_follow_proto_rawDescData
}

var file_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_follow_proto_goTypes = []any{
	(*FollowRequest)(nil),      // 0: user.FollowRequest
	(*FollowResponse)(nil),     // 1: user.FollowResponse
	(*UnFollowRequest)(nil),    // 2: user.UnFollowRequest
	(*UnFollowResponse)(nil),   // 3: user.UnFollowResponse
	(*FollowListRequest)(nil),  // 4: user.FollowListRequest
	(*FollowItem)(nil),         // 5: user.FollowItem
	(*FollowListData)(nil),     // 6: user.FollowListData
	(*FollowListResponse)(nil), // 7: user.FollowListResponse
	(*FansListRequest)(nil),    // 8: user.FansListRequest
	(*FansItem)(nil),           // 9: user.FansItem
	(*FansListData)(nil),       // 10: user.FansListData
	(*FansListResponse)(nil),   // 11: user.FansListResponse
}
var file_follow_proto_depIdxs = []int32{
	5,  // 0: user.FollowListData.items:type_name -> user.FollowItem
	6,  // 1: user.FollowListResponse.data:type_name -> user.FollowListData
	9,  // 2: user.FansListData.items:type_name -> user.FansItem
	10, // 3: user.FansListResponse.data:type_name -> user.FansListData
	0,  // 4: user.Follow.Follow:input_type -> user.FollowRequest
	2,  // 5: user.Follow.UnFollow:input_type -> user.UnFollowRequest
	4,  // 6: user.Follow.FollowList:input_type -> user.FollowListRequest
	8,  // 7: user.Follow.FansList:input_type -> user.FansListRequest
	1,  // 8: user.Follow.Follow:output_type -> user.FollowResponse
	3,  // 9: user.Follow.UnFollow:output_type -> user.UnFollowResponse
	7,  // 10: user.Follow.FollowList:output_type -> user.FollowListResponse
	11, // 11: user.Follow.FansList:output_type -> user.FansListResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_follow_proto_init() }
func file_follow_proto_init() {
	if File_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follow_proto_goTypes,
		DependencyIndexes: file_follow_proto_depIdxs,
		MessageInfos:      file_follow_proto_msgTypes,
	}.Build()
	File_follow_proto = out.File
	file_follow_proto_goTypes = nil
	file_follow_proto_depIdxs = nil
}
